From bugzilla-daemon at main.slony.info  Wed Sep  7 08:48:04 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed,  7 Sep 2011 08:48:04 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 238] New: Draw in Copyright Update script from
	PostgreSQL
Message-ID: <bug-238-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=238

           Summary: Draw in Copyright Update script from PostgreSQL
           Product: Slony-I
           Version: devel
          Platform: All
        OS/Version: All
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: other scripts
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: cbbrowne at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


A script has been added to PostgreSQL as a "helper" to automatically update
copyright dates throughout the code base.

https://commitfest.postgresql.org/action/patch_view?id=619

We can probably use this, too.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Sep  7 10:03:03 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed,  7 Sep 2011 10:03:03 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 238] Draw in Copyright Update script from
	PostgreSQL
In-Reply-To: <bug-238-4@http.www.slony.info/bugzilla/>
References: <bug-238-4@http.www.slony.info/bugzilla/>
Message-ID: <20110907170303.9E94B290E30@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=238

--- Comment #1 from Christopher Browne <cbbrowne at ca.afilias.info> 2011-09-07 10:03:03 PDT ---
Created branch @ github capturing the file added to PostgreSQL

https://github.com/cbbrowne/slony1-engine/commit/78739a21e25bc6b060457da314dc5bbcdbb7469a

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Sep  7 10:04:19 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed,  7 Sep 2011 10:04:19 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 238] Draw in Copyright Update script from
	PostgreSQL
In-Reply-To: <bug-238-4@http.www.slony.info/bugzilla/>
References: <bug-238-4@http.www.slony.info/bugzilla/>
Message-ID: <20110907170419.E467B290E30@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=238

--- Comment #2 from Christopher Browne <cbbrowne at ca.afilias.info> 2011-09-07 10:04:19 PDT ---
Created an attachment (id=126)
 --> (http://www.slony.info/bugzilla/attachment.cgi?id=126)
Sample of diff when copyright.pl is run against Slony

Here is a sample of what is generated.  The code changes look fine.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Tue Sep 20 05:16:19 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Tue, 20 Sep 2011 05:16:19 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 239] New: Slony 1.2.22 and PG9.0 shows failure
	at failover
Message-ID: <bug-239-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=239

           Summary: Slony 1.2.22 and PG9.0 shows failure at failover
           Product: Slony-I
           Version: 1.2
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: blocker
          Priority: low
         Component: slonik
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: reena.madan at enterprisedb.com
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


With combination of PG9.0 and Slony1.2.22, Failover fails to complete
successfully.

During failover pg_listener is being looked for whereas  "pg_listener" has been
removed starting 9.0.

Error seen during failover:
# slonik failover 
failover:6: PGRES_FATAL_ERROR lock table "_edb_cluster".sl_config_lock; select
listenerpid from "pg_catalog".pg_listener     where relname =
'_edb_cluster_Restart';  - ERROR:  relation "pg_catalog.pg_listener" does not
exist
LINE 1: ..._cluster".sl_config_lock; select listenerpid from "pg_catalo...

Replication of data from master to slave works good as well as switchover works
fine.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Tue Sep 20 05:17:11 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Tue, 20 Sep 2011 05:17:11 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 239] Slony 1.2.22 and PG9.0 shows failure at
	failover
In-Reply-To: <bug-239-4@http.www.slony.info/bugzilla/>
References: <bug-239-4@http.www.slony.info/bugzilla/>
Message-ID: <20110920121711.5696A290E59@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=239

reena.madan at enterprisedb.com changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
           Priority|low                         |high

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Sep 21 12:20:40 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 21 Sep 2011 12:20:40 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 240] New: Need better documentation of auto
 vacuum interaction with Slony
Message-ID: <bug-240-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=240

           Summary: Need better documentation of auto vacuum interaction
                    with Slony
           Product: Slony-I
           Version: devel
          Platform: All
        OS/Version: All
            Status: ASSIGNED
          Severity: enhancement
          Priority: low
         Component: docs
        AssignedTo: cbbrowne at ca.afilias.info
        ReportedBy: cbbrowne at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


Questions have come up on list; it looks like a section describing how vacuum
is handled should be added to Deployment Considerations.

This should include describing:
- What are the parameters?
- What do you need to configure on tables to make them autovac (or not)?
- What is recommended?

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.

From bugzilla-daemon at main.slony.info  Thu Sep 22 12:48:43 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Thu, 22 Sep 2011 12:48:43 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 239] Slony 1.2.22 and PG9.0 shows failure at
	failover
In-Reply-To: <bug-239-4@http.www.slony.info/bugzilla/>
References: <bug-239-4@http.www.slony.info/bugzilla/>
Message-ID: <20110922194843.AD4D12903C6@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=239

Steve Singer <ssinger at ca.afilias.info> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
         AssignedTo|slony1-bugs at lists.slony.inf |ssinger at ca.afilias.info
                   |o                           |
             Status|NEW                         |ASSIGNED

--- Comment #1 from Steve Singer <ssinger at ca.afilias.info> 2011-09-22 12:48:43 PDT ---
Created an attachment (id=127)
 --> (http://www.slony.info/bugzilla/attachment.cgi?id=127)
Proposed fix

Attached is a proposed fix to get 1.2 working on Postgresql 9.0

Please verify that a) this fixes your problem and b) things work okay on other
versions of postgresql

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Mon Sep 26 05:59:15 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Mon, 26 Sep 2011 05:59:15 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 239] Slony 1.2.22 and PG9.0 shows failure at
	failover
In-Reply-To: <bug-239-4@http.www.slony.info/bugzilla/>
References: <bug-239-4@http.www.slony.info/bugzilla/>
Message-ID: <20110926125915.BBA7E290E5A@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=239

--- Comment #2 from reena.madan at enterprisedb.com 2011-09-26 05:59:15 PDT ---
I have verified slony 1.2.22 +patch with Postgresql 9.0 and it works for
failover and switchover back and forth.
Will need to check it with other versions of postgresql too.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.

From bugzilla-daemon at main.slony.info  Tue Sep 27 02:20:42 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Tue, 27 Sep 2011 02:20:42 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 239] Slony 1.2.22 and PG9.0 shows failure at
	failover
In-Reply-To: <bug-239-4@http.www.slony.info/bugzilla/>
References: <bug-239-4@http.www.slony.info/bugzilla/>
Message-ID: <20110927092043.00707290E55@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=239

--- Comment #3 from reena.madan at enterprisedb.com 2011-09-27 02:20:42 PDT ---
I have verified it with PG8.4.9 version and Switchover/Failover all work well.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.

From bugzilla-daemon at main.slony.info  Wed Sep 28 08:22:31 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 28 Sep 2011 08:22:31 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 241] New: bad output for filename in slonik echo
	output
Message-ID: <bug-241-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=241

           Summary: bad output for filename in slonik echo output
           Product: Slony-I
           Version: 2.0
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: slonik
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: ssinger at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


As reported on the mailing list.

http://lists.slony.info/pipermail/slony1-general/2011-September/011870.html
=======
Its version 2.0.7

u2_newslave.sk:

    include <u2_preamble.sk>;
    include <gen_newslave.sk>;


u2_preamble.sk:

    cluster name = sl;

    define node1_conninfo 'blah blah blah';
    define node2_conninfo 'more blah';

    node 1 admin conninfo = @node1_conninfo;
    node 2 admin conninfo = @node2_conninfo;


gen_newslave.sk:

    include <gen_sync.sk>;

    echo 'Adding node 2';
    store node (id=2, comment=@node2_conninfo, event node=1);
    echo 'Creating paths';
    store path (server=1, client=2, conninfo=@node1_conninfo);
    store path (server=2, client=1, conninfo=@node2_conninfo);
    include <gen_sync.sk>;

    echo 'Subscribing node 2';
    subscribe set (id=1,provider=1,receiver=2,forward=yes);
    wait for event (origin=1, confirmed=all, wait on=1, timeout=0);
    echo 'Subscription created. Slave is copying data. Master can go live.';


gen_sync.sk:

    echo 'Waiting for sync';
    sync (id=1);
    wait for event (origin=1, confirmed=all, wait on=1, timeout=0);
    echo 'Synced';


Results in

$ slonik u2_newslave.sk
:1: Waiting for sync
:4: Synced
gen_newslave.sk:3: Adding node 2
gen_newslave.sk:5: Creating paths
Subscribing node 2:1: Waiting for sync
Subscribing node 2:4: Synced
/lib/libnsl.so.1:10: Subscribing node 2
/lib/libnsl.so.1:13: Subscription created. Slave is copying data. Master can go
live.


========================

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Sep 28 08:26:05 2011
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 28 Sep 2011 08:26:05 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 241] bad output for filename in slonik echo
	output
In-Reply-To: <bug-241-4@http.www.slony.info/bugzilla/>
References: <bug-241-4@http.www.slony.info/bugzilla/>
Message-ID: <20110928152605.82C95290E2C@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=241

--- Comment #1 from Steve Singer <ssinger at ca.afilias.info> 2011-09-28 08:26:05 PDT ---
I *THINK the problem here is that

in scan.l when processing an include directive we strdup() the filename and
pass this to pushBuffer().  This sets current_file to the memory allocated by
strdup.  As the parser runs it stores a pointer to current_file into the
structures that the parser creates.

When processing of that file ends popBuffer() calls free(current_file).  This
will deallocate the memory even though the structures created by the parser
still might point at that memory.

In parser.y should we be calling strdup(current_file) to create a new copy of
the filename for storing in the parser structures?

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

