From bugzilla-daemon at main.slony.info  Wed Oct  1 12:09:31 2014
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed,  1 Oct 2014 12:09:31 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 351] New: have Store Node error out if there is
 already a Slony cluster
Message-ID: <bug-351-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=351

           Summary: have Store Node error out if there is already a Slony
                    cluster
           Product: Slony-I
           Version: devel
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: slonik
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: cbbrowne at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


But with an option to force the matter for the rare cases where someone truly
wants an extra replication cluster...

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Thu Oct  2 08:43:55 2014
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Thu,  2 Oct 2014 08:43:55 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 352] New: Postgres HEAD refactored INT64_FORMAT
 out of pg_config.h
Message-ID: <bug-352-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=352

           Summary: Postgres HEAD refactored INT64_FORMAT out of
                    pg_config.h
           Product: Slony-I
           Version: devel
          Platform: All
        OS/Version: All
            Status: NEW
          Severity: major
          Priority: low
         Component: slon
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: cbbrowne at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


In commit ce486056ecd28050f367894a2b5aad3656d37511, INT64_FORMAT was removed
from 
pg_config.h, added to c.h, which is inappropriate for us to #include in Slony.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Thu Oct  2 08:45:55 2014
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Thu,  2 Oct 2014 08:45:55 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 352] Postgres HEAD refactored INT64_FORMAT out
	of pg_config.h
In-Reply-To: <bug-352-4@http.www.slony.info/bugzilla/>
References: <bug-352-4@http.www.slony.info/bugzilla/>
Message-ID: <20141002154555.BD9B2291712@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=352

Christopher Browne <cbbrowne at ca.afilias.info> changed:

           What    |Removed                     |Added
----------------------------------------------------------------------------
         AssignedTo|slony1-bugs at lists.slony.inf |cbbrowne at ca.afilias.info
                   |o                           |

--- Comment #1 from Christopher Browne <cbbrowne at ca.afilias.info> 2014-10-02 08:45:55 PDT ---
Created an attachment (id=205)
 --> (http://www.slony.info/bugzilla/attachment.cgi?id=205)
Define INT64_FORMAT if not provided by pg_config.h

This approach requires no configure changes.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Oct 15 12:47:44 2014
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 15 Oct 2014 12:47:44 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 353] New: Health check - checkpoint configuration
Message-ID: <bug-353-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=353

           Summary: Health check - checkpoint configuration
           Product: Slony-I
           Version: devel
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: slon
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: cbbrowne at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


At startup time, should compare the checkpoint interval with the cleanup thread
interval, and warn of problems if checkpoint < 5 x cleanup interval.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Oct 22 15:31:53 2014
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 22 Oct 2014 15:31:53 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 354] New: failover can get stuck waiting for
 events after sl_listen is empty
Message-ID: <bug-354-4@http.www.slony.info/bugzilla/>

http://www.slony.info/bugzilla/show_bug.cgi?id=354

           Summary: failover can get stuck waiting for events after
                    sl_listen is empty
           Product: Slony-I
           Version: devel
          Platform: PC
        OS/Version: Linux
            Status: NEW
          Severity: enhancement
          Priority: low
         Component: stored procedures
        AssignedTo: slony1-bugs at lists.slony.info
        ReportedBy: ssinger at ca.afilias.info
                CC: slony1-bugs at lists.slony.info
   Estimated Hours: 0.0


This applies to the 2.2 branch and master

Consider a cluster where node 1 is the origin of all sets

1-->2
|
3->5
|
4

FAILOVER(id=5,backup node=5);

Where we are failing over a non-origin.

The remote worker for a node like node 4 might receiver an event from node 1

FAILOVER_NODE, 5, 5000001234)
That says the node 5 has failed and the last event from node 5 that node 1 has
seen is 5000001234

Now if node 4 gets the failover over before 5,5000001234
then the the remoteWorker_1 will call the failedNode() stored function on node
4.

Then it will wait for  5,5000001234.  However if slon then restarts the slon
will never process 5,5000001234 (a restart might not even be required but that
is how I've seen this)

The failedNode() call erased all the sl_listen entires with li_origin=5
select * FROM _disorder_replica.sl_listen where li_origin=5;
 li_origin | li_provider | li_receiver 
-----------+-------------+-------------
(0 rows)

None of the remoteListener threads will be listening for events from node 5 so
the misisng SYNC will never get processed.  The SYNC probably contains no data
because 5 is not an origin but the failover event is stuck.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Oct 22 15:33:53 2014
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 22 Oct 2014 15:33:53 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 354] failover can get stuck waiting for events
 after sl_listen is empty
In-Reply-To: <bug-354-4@http.www.slony.info/bugzilla/>
References: <bug-354-4@http.www.slony.info/bugzilla/>
Message-ID: <20141022223353.459F32917DC@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=354

--- Comment #1 from Steve Singer <ssinger at ca.afilias.info> 2014-10-22 15:33:53 PDT ---
In RebuildListenNetwork we have the following comment

    --for every failed node we delete all sl_listen entries
        --except via providers (listed in sl_subscribe)
        --or failover candidates (sl_failover_targets)
        --we do this to prevent a non-failover candidate
        --that is more ahead of the failover candidate from
        --sending events to the failover candidate that
        --are 'too far ahead'

    delete from @NAMESPACE at .sl_listen where
               li_origin=v_row.origin and
               li_receiver=v_row.receiver            
               and li_provider not in 
                   (select sub_provider from
                   @NAMESPACE at .sl_subscribe,
                   @NAMESPACE at .sl_set where
                   sub_set=set_id
                   and set_origin=v_row.origin);

node 5 isn't a provider of anything so the listen network is erased.

I think this is wrong.

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

From bugzilla-daemon at main.slony.info  Wed Oct 22 17:57:49 2014
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Wed, 22 Oct 2014 17:57:49 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 352] Postgres HEAD refactored INT64_FORMAT out
	of pg_config.h
In-Reply-To: <bug-352-4@http.www.slony.info/bugzilla/>
References: <bug-352-4@http.www.slony.info/bugzilla/>
Message-ID: <20141023005749.639772917DC@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=352

--- Comment #2 from Steve Singer <ssinger at ca.afilias.info> 2014-10-22 17:57:49 PDT ---
Created an attachment (id=206)
 --> (http://www.slony.info/bugzilla/attachment.cgi?id=206)
include postgres_fe (DRAFT)

This is another approach we could take
include postgres_fe.h which picks up the location that INT64_FORMAT has been
moved to.

Including postgres_fe.h mean that we need to use the SERVER include paths when
building slonik and slon.  We do this anyway if we are building with pgport (so
to build with this patch do --with-pgport on the configure line)

If we go with that approach we'd make both pgport and non-pgport builds use
those

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.

From bugzilla-daemon at main.slony.info  Mon Oct 27 14:03:39 2014
From: bugzilla-daemon at main.slony.info (bugzilla-daemon at main.slony.info)
Date: Mon, 27 Oct 2014 14:03:39 -0700 (PDT)
Subject: [Slony1-bugs] [Bug 354] failover can get stuck waiting for events
 after sl_listen is empty
In-Reply-To: <bug-354-4@http.www.slony.info/bugzilla/>
References: <bug-354-4@http.www.slony.info/bugzilla/>
Message-ID: <20141027210339.A00D92917CA@main.slony.info>

http://www.slony.info/bugzilla/show_bug.cgi?id=354

--- Comment #2 from Steve Singer <ssinger at ca.afilias.info> 2014-10-27 14:03:39 PDT ---
Created an attachment (id=207)
 --> (http://www.slony.info/bugzilla/attachment.cgi?id=207)
proposed patch

-- 
Configure bugmail: http://www.slony.info/bugzilla/userprefs.cgi?tab=email
------- You are receiving this mail because: -------
You are on the CC list for the bug.
You are the assignee for the bug.

