From JanWieck at Yahoo.com  Mon Dec  3 14:24:35 2012
From: JanWieck at Yahoo.com (Jan Wieck)
Date: Mon, 03 Dec 2012 17:24:35 -0500
Subject: [Slony1-general] Slony version 2.1.0 switchover
In-Reply-To: <50B8D902.60804@ca.afilias.info>
References: <EE2CCD4592BF824BAE17A02DFAAC74FA1DC51775@BLUPRD0711MB401.namprd07.prod.outlook.com>
	<50B8D902.60804@ca.afilias.info>
Message-ID: <50BD26A3.30301@Yahoo.com>

On 11/30/2012 11:04 AM, Steve Singer wrote:
> On 12-11-27 11:59 AM, Frank McGeough wrote:
>> I'm writing to ask about using Slony switchover capability. I've never
>> actually been able to make this work. I'm curious about whether this is
>> a common experience or if, perhaps, there is something that I don't
>> understand about how this should function. The environment that I have
>> is a database that is in constant use. That is, there is always at least
>> a low level of DML (inserts for the most part) occurring 24 x 7, 365
>> days a year. I've found that Slony will never be able to get a lock in
>> order to perform the switchover and thus I'm left with tearing
>
> The slony MOVE SET operation needs to have an exclusive lock on all
> tables in the set at the same time.   The recommended way of doing this
> is to have your application stop traffic to the database for long enough
> so that this can be done, and then wait for the event to propogate to
> the new master and then have your application start queries against the
> new master.
>
> If slony gets its locks on a move set in this order
> Table1
> Table2
> Table3
>
> but your application access tables in this order
> Table3
> Table2
> Table1
>
> Your application and slony will deadlock each other.

What Steve said.

Also, if your application is compatible with pgbouncer's transaction 
mode (i.e. not using server side prepared statements), then you can use 
that to PAUSE and RESUME the real database connections without even 
stopping the application. This can be completely scripted and pgbouncer 
can even do the redirection of traffic on RESUME.


Jan

-- 
Anyone who trades liberty for security deserves neither
liberty nor security. -- Benjamin Franklin

From drees76 at gmail.com  Tue Dec  4 12:13:11 2012
From: drees76 at gmail.com (David Rees)
Date: Tue, 4 Dec 2012 12:13:11 -0800
Subject: [Slony1-general] Multiple sets w/same table
Message-ID: <CAHtT9RuY9OYbRyE=D80f++RErqT+GpBc+byfDMzSH8bwiu=zzQ@mail.gmail.com>

For some reason I thought this was possible, but I'm running into problems.

3 nodes (2 pg 8.4, one 9.0) all running slony 2.1.2.
The same database schema is on all 3 nodes.
Set 1 consists of all tables in the database - node 2 subscribes to
set 1 from node 1.
Set 2 consists of a subset of the tables in the database - node 3
subscribes to set 2 from node 2.

The problem is that when I try to create set 2, slony complains
'ERROR:  duplicate key value violates unique constraint
"sl_table_tab_reloid_key"'

Looking at sl_table_tab_reloid_key it appears that this key would
prevent any single table from being in multiple sets.

In which case, I believe that I could work around this by using a
different cluster for set 2.

Or am I missing something?

Thank you!

Dave

From steve at ssinger.info  Tue Dec  4 19:34:12 2012
From: steve at ssinger.info (Steve Singer)
Date: Tue, 4 Dec 2012 22:34:12 -0500
Subject: [Slony1-general] Multiple sets w/same table
In-Reply-To: <CAHtT9RuY9OYbRyE=D80f++RErqT+GpBc+byfDMzSH8bwiu=zzQ@mail.gmail.com>
References: <CAHtT9RuY9OYbRyE=D80f++RErqT+GpBc+byfDMzSH8bwiu=zzQ@mail.gmail.com>
Message-ID: <BLU0-SMTP20818CE4A2C25BABF659562DC460@phx.gbl>

On Tue, 4 Dec 2012, David Rees wrote:

> For some reason I thought this was possible, but I'm running into problems.
>
> 3 nodes (2 pg 8.4, one 9.0) all running slony 2.1.2.
> The same database schema is on all 3 nodes.
> Set 1 consists of all tables in the database - node 2 subscribes to
> set 1 from node 1.
> Set 2 consists of a subset of the tables in the database - node 3
> subscribes to set 2 from node 2.

Why don't you put your subset of tables in set 2, the rest of the tables in 
set 1.  Then

subscribe set(set id=1, provider=1,provider=2)
subscribe set(set id=2, provider=1,provider=2)
subscibe set(set id=2,provider=2,receiver=3)

You can't have the same table in multiple sets, but a node can subscribe to 
multiple sets.


>
> The problem is that when I try to create set 2, slony complains
> 'ERROR:  duplicate key value violates unique constraint
> "sl_table_tab_reloid_key"'
>
> Looking at sl_table_tab_reloid_key it appears that this key would
> prevent any single table from being in multiple sets.
>
> In which case, I believe that I could work around this by using a
> different cluster for set 2.
>
> Or am I missing something?
>
> Thank you!
>
> Dave
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general
>


From drees76 at gmail.com  Tue Dec  4 20:50:29 2012
From: drees76 at gmail.com (David Rees)
Date: Tue, 4 Dec 2012 20:50:29 -0800
Subject: [Slony1-general] Multiple sets w/same table
In-Reply-To: <BLU0-SMTP20818CE4A2C25BABF659562DC460@phx.gbl>
References: <CAHtT9RuY9OYbRyE=D80f++RErqT+GpBc+byfDMzSH8bwiu=zzQ@mail.gmail.com>
	<BLU0-SMTP20818CE4A2C25BABF659562DC460@phx.gbl>
Message-ID: <CAHtT9RsANTGpan9ovnF-Evfvur71hoGRMAOdrJAs39TY6FfrMw@mail.gmail.com>

On Tue, Dec 4, 2012 at 7:34 PM, Steve Singer <steve at ssinger.info> wrote:
> On Tue, 4 Dec 2012, David Rees wrote:
>> For some reason I thought this was possible, but I'm running into
>> problems.
>>
>> 3 nodes (2 pg 8.4, one 9.0) all running slony 2.1.2.
>> The same database schema is on all 3 nodes.
>> Set 1 consists of all tables in the database - node 2 subscribes to
>> set 1 from node 1.
>> Set 2 consists of a subset of the tables in the database - node 3
>> subscribes to set 2 from node 2.
>
> Why don't you put your subset of tables in set 2, the rest of the tables in
> set 1.  Then
>
> subscribe set(set id=1, provider=1,provider=2)
> subscribe set(set id=2, provider=1,provider=2)
> subscibe set(set id=2,provider=2,receiver=3)
>
> You can't have the same table in multiple sets, but a node can subscribe to
> multiple sets.

Thanks - after some playing around (tried a separate cluster which
didn't work - no changes were propagated to node 3.

There are some foreign keys which exist on node 1/2 which would cross
the 2 sets (node 3 doesn't have those foreign keys) - are there any
issues with consistency or will all changes to the database still be
committed in the same order as they occurred on the originating node?

For example, table 1 is in set 1 and table 2 is in set 2 and table 1
has a foreign key that refers to table 2.

Changes that occur on the origin node 1 which will be the same for set
1/2 will obviously be fine, but is it possible for an event to be
committed out-of-order on node 2?

Thank you!

Dave

From ssinger at ca.afilias.info  Thu Dec  6 15:06:08 2012
From: ssinger at ca.afilias.info (Steve Singer)
Date: Thu, 06 Dec 2012 18:06:08 -0500
Subject: [Slony1-general] Multiple sets w/same table
In-Reply-To: <CAHtT9RsANTGpan9ovnF-Evfvur71hoGRMAOdrJAs39TY6FfrMw@mail.gmail.com>
References: <CAHtT9RuY9OYbRyE=D80f++RErqT+GpBc+byfDMzSH8bwiu=zzQ@mail.gmail.com>
	<BLU0-SMTP20818CE4A2C25BABF659562DC460@phx.gbl>
	<CAHtT9RsANTGpan9ovnF-Evfvur71hoGRMAOdrJAs39TY6FfrMw@mail.gmail.com>
Message-ID: <50C124E0.7000409@ca.afilias.info>

On 12-12-04 11:50 PM, David Rees wrote:
> On Tue, Dec 4, 2012 at 7:34 PM, Steve Singer <steve at ssinger.info> wrote:


>
> For example, table 1 is in set 1 and table 2 is in set 2 and table 1
> has a foreign key that refers to table 2.
>
> Changes that occur on the origin node 1 which will be the same for set
> 1/2 will obviously be fine, but is it possible for an event to be
> committed out-of-order on node 2?
>

If you subscribe  set 2 first, then set 1 and if both set 1 and your not 
using a different forwarder node, then I think you should be okay.


> Thank you!
>
> Dave
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general
>


From drees76 at gmail.com  Thu Dec  6 15:11:52 2012
From: drees76 at gmail.com (David Rees)
Date: Thu, 6 Dec 2012 15:11:52 -0800
Subject: [Slony1-general] Multiple sets w/same table
In-Reply-To: <50C124E0.7000409@ca.afilias.info>
References: <CAHtT9RuY9OYbRyE=D80f++RErqT+GpBc+byfDMzSH8bwiu=zzQ@mail.gmail.com>
	<BLU0-SMTP20818CE4A2C25BABF659562DC460@phx.gbl>
	<CAHtT9RsANTGpan9ovnF-Evfvur71hoGRMAOdrJAs39TY6FfrMw@mail.gmail.com>
	<50C124E0.7000409@ca.afilias.info>
Message-ID: <CAHtT9Rs0Wb1q5rnh8QVkOLV1E=h5DD7S-EYNLHfa17N_f9z_VA@mail.gmail.com>

On Thu, Dec 6, 2012 at 3:06 PM, Steve Singer <ssinger at ca.afilias.info> wrote:
> On 12-12-04 11:50 PM, David Rees wrote:
>> On Tue, Dec 4, 2012 at 7:34 PM, Steve Singer <steve at ssinger.info> wrote:
>> For example, table 1 is in set 1 and table 2 is in set 2 and table 1
>> has a foreign key that refers to table 2.
>>
>> Changes that occur on the origin node 1 which will be the same for set
>> 1/2 will obviously be fine, but is it possible for an event to be
>> committed out-of-order on node 2?
>
> If you subscribe  set 2 first, then set 1 and if both set 1 and your not
> using a different forwarder node, then I think you should be okay.

Thanks - I'll give it a shot in a test environment first.

-Dave

From JanWieck at Yahoo.com  Sun Dec  9 09:33:16 2012
From: JanWieck at Yahoo.com (Jan Wieck)
Date: Sun, 09 Dec 2012 12:33:16 -0500
Subject: [Slony1-general] Multiple sets w/same table
In-Reply-To: <50C124E0.7000409@ca.afilias.info>
References: <CAHtT9RuY9OYbRyE=D80f++RErqT+GpBc+byfDMzSH8bwiu=zzQ@mail.gmail.com>
	<BLU0-SMTP20818CE4A2C25BABF659562DC460@phx.gbl>
	<CAHtT9RsANTGpan9ovnF-Evfvur71hoGRMAOdrJAs39TY6FfrMw@mail.gmail.com>
	<50C124E0.7000409@ca.afilias.info>
Message-ID: <50C4CB5C.9060901@Yahoo.com>

On 12/6/2012 6:06 PM, Steve Singer wrote:
> On 12-12-04 11:50 PM, David Rees wrote:
>> On Tue, Dec 4, 2012 at 7:34 PM, Steve Singer <steve at ssinger.info> wrote:
>
>
>>
>> For example, table 1 is in set 1 and table 2 is in set 2 and table 1
>> has a foreign key that refers to table 2.
>>
>> Changes that occur on the origin node 1 which will be the same for set
>> 1/2 will obviously be fine, but is it possible for an event to be
>> committed out-of-order on node 2?
>>
>
> If you subscribe  set 2 first, then set 1 and if both set 1 and your not
> using a different forwarder node, then I think you should be okay.

The subscriptions should work either way since it is done under 
session_replication_role=replica, which suppresses foreign key checks.


Jan

-- 
Anyone who trades liberty for security deserves neither
liberty nor security. -- Benjamin Franklin

From Ger.Timmens at adyen.com  Mon Dec 10 08:53:13 2012
From: Ger.Timmens at adyen.com (Ger Timmens)
Date: Mon, 10 Dec 2012 17:53:13 +0100
Subject: [Slony1-general] Slony memory leak
In-Reply-To: <mailman.1.1355083201.25366.slony1-general@lists.slony.info>
References: <mailman.1.1355083201.25366.slony1-general@lists.slony.info>
Message-ID: <50C61379.905@adyen.com>

All,

Running slony1 2.1.1 on x86_64 in forwarding mode;
Slony itself is running fine, but the slon processes are taking
more and more memory each day, resulting in an OOM exception.

Workaround for now is restarting the slon processes once in a while / by
cron.

Regards,

Ger

-- 
Ger Timmens
Adyen - Payments Made Easy
http://www.adyen.com

Visiting Address: Kantoorgebouw Nijenburg  Mail Address:
Simon Carmiggeltstraat 6-50, 5th floor      P.O. Box 10095
1011 DJ Amsterdam                          1001 EB Amsterdam
The Netherlands                            The Netherlands

Direct +31.20.240.1248
Office +31.20.240.1240
Mobile +31.62.483.8468
Email ger.timmens at adyen.com



From ssinger at ca.afilias.info  Mon Dec 10 09:02:16 2012
From: ssinger at ca.afilias.info (Steve Singer)
Date: Mon, 10 Dec 2012 12:02:16 -0500
Subject: [Slony1-general] Slony memory leak
In-Reply-To: <50C61379.905@adyen.com>
References: <mailman.1.1355083201.25366.slony1-general@lists.slony.info>
	<50C61379.905@adyen.com>
Message-ID: <50C61598.70708@ca.afilias.info>

On 12-12-10 11:53 AM, Ger Timmens wrote:
> All,
>
> Running slony1 2.1.1 on x86_64 in forwarding mode;
> Slony itself is running fine, but the slon processes are taking
> more and more memory each day, resulting in an OOM exception.
>
> Workaround for now is restarting the slon processes once in a while / by
> cron.

It might be
http://bugs.slony.info/bugzilla/show_bug.cgi?id=275

You can turn off the monitor thread in the slon.conf file and that stops 
the leaking.


>
> Regards,
>
> Ger
>


From tmblue at gmail.com  Mon Dec 10 14:28:11 2012
From: tmblue at gmail.com (Tory M Blue)
Date: Mon, 10 Dec 2012 14:28:11 -0800
Subject: [Slony1-general] data copy for set 1 failed 3 times - sleep 60
	seconds
In-Reply-To: <CAEaSS0bCWq+88mMnpt2+uzGK7-YuaOCW60WzupPiLuXR5QexnA@mail.gmail.com>
References: <CAEaSS0ZsK9inShCY9CR2X4fOwHeGzO7qGSmT2LbFmXsXy+R0yA@mail.gmail.com>
	<1354179426.14986.YahooMailNeo@web133202.mail.ir2.yahoo.com>
	<CAEaSS0aZi=zGZZADEDwVOM4nLRpP6C0cncCknyQBfJm8kTD+Ng@mail.gmail.com>
	<50B7A63B.3070804@ca.afilias.info>
	<CAEaSS0aLVWiDJ43dKjbfzq3Ldne2D07EQDEvTZrSVTpK84uFCg@mail.gmail.com>
	<50B7E03A.5040705@ca.afilias.info>
	<CAEaSS0apzgrdUv6ExkW3nf+TfQbcGQjvg32pvmY_q9QkQV3ATg@mail.gmail.com>
	<50B8C526.7090802@ca.afilias.info>
	<CAEaSS0bCWq+88mMnpt2+uzGK7-YuaOCW60WzupPiLuXR5QexnA@mail.gmail.com>
Message-ID: <CAEaSS0aLOxufMA2eqG5du2Nfk4LfFRWGo22YvdTwP7EmjaYTzg@mail.gmail.com>

I'm back to it with debug of 4 on the source and the destination nodes.

Still failing

Destination:

Slon log:

2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: 6525.754 seconds to
copy table "cls"."listings"
2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: copy table
"cls"."customers"
2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: Begin COPY of table
"cls"."customers"
2012-12-10 12:04:49 PST ERROR  remoteWorkerThread_1: "select
"_admissioncls".copyFields(8);"
2012-12-10 12:04:49 PST WARN   remoteWorkerThread_1: data copy for set 1
failed 1 times - sleep 15 seconds
2012-12-10 12:04:51 PST INFO   cleanupThread: 5961.364 seconds for
cleanupEvent()
2012-12-10 12:05:06 PST INFO   copy_set 1 - omit=f - bool=0
2012-12-10 12:05:06 PST INFO   omit is FALSE
2012-12-10 12:05:06 PST CONFIG version for "dbname=clsdb host=server
user=postgres password=SECURED is 90104
2012-12-10 12:05:07 PST DEBUG1 copy_set_1 "dbname=clsdb host=server
user=postgres password=SECURED": backend pid = 17092
2012-12-10 12:05:07 PST CONFIG remoteWorkerThread_1: connected to provider
DB

Postgres logs:

2012-12-10 12:04:51 PST admissionclsdb postgres [local] NOTICE:  Slony-I:
Logswitch to sl_log_2 initiated
2012-12-10 12:04:51 PST admissionclsdb postgres [local] CONTEXT:  SQL
statement "SELECT "_admissioncls".logswitch_start()"
2012-12-10 12:05:12 PST admissionclsdb postgres [local] LOG:  sending
cancel to blocking autovacuum PID 18620
2012-12-10 12:05:12 PST admissionclsdb postgres [local] DETAIL:  Process
18299 waits for AccessExclusiveLock on relation 17410 of database 16385.
2012-12-10 12:05:12 PST admissionclsdb postgres [local] STATEMENT:  lock
table "cls"."listings";
2012-12-10 12:05:12 PST    ERROR:  canceling autovacuum task
2012-12-10 12:05:12 PST    CONTEXT:  automatic vacuum of table
"admissionclsdb.cls.listings"
2012-12-10 12:05:12 PST admissionclsdb postgres [local] NOTICE:  truncate
of "cls"."autobodystyle" succeeded


Source:

There is nothing in the slon log that would tell me it's aware of this
client side restart or failure. Nothing in the postgres logs about an EOF
or anything.
Nothing in postgres log either that says there is an issue.

This is not a connection firewall thing. Since I have a table that will
take 4 hours and upon it's completion the process fails and starts over.
This file above is just about an hour, completes and then starts on another
before it says fail.

I'm wondering.. "Could" it be that for the first time, trying to replicate
from Postgres 9.1.4 to 9.1.6 there is an underlying issue? That is the only
difference in my various environments (the destination in this case is
running 9.1.6).

I'm up to trying anything, any ideas?

Thanks again and I appreciate the patience
Tory
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20121210/5c4ac46f/attachment.html 

From JanWieck at Yahoo.com  Mon Dec 10 14:55:01 2012
From: JanWieck at Yahoo.com (Jan Wieck)
Date: Mon, 10 Dec 2012 17:55:01 -0500
Subject: [Slony1-general] data copy for set 1 failed 3 times - sleep 60
 seconds
In-Reply-To: <CAEaSS0aLOxufMA2eqG5du2Nfk4LfFRWGo22YvdTwP7EmjaYTzg@mail.gmail.com>
References: <CAEaSS0ZsK9inShCY9CR2X4fOwHeGzO7qGSmT2LbFmXsXy+R0yA@mail.gmail.com>
	<1354179426.14986.YahooMailNeo@web133202.mail.ir2.yahoo.com>
	<CAEaSS0aZi=zGZZADEDwVOM4nLRpP6C0cncCknyQBfJm8kTD+Ng@mail.gmail.com>
	<50B7A63B.3070804@ca.afilias.info>
	<CAEaSS0aLVWiDJ43dKjbfzq3Ldne2D07EQDEvTZrSVTpK84uFCg@mail.gmail.com>
	<50B7E03A.5040705@ca.afilias.info>
	<CAEaSS0apzgrdUv6ExkW3nf+TfQbcGQjvg32pvmY_q9QkQV3ATg@mail.gmail.com>
	<50B8C526.7090802@ca.afilias.info>
	<CAEaSS0bCWq+88mMnpt2+uzGK7-YuaOCW60WzupPiLuXR5QexnA@mail.gmail.com>
	<CAEaSS0aLOxufMA2eqG5du2Nfk4LfFRWGo22YvdTwP7EmjaYTzg@mail.gmail.com>
Message-ID: <50C66845.80006@Yahoo.com>

On 12/10/2012 5:28 PM, Tory M Blue wrote:
>
> I'm back to it with debug of 4 on the source and the destination nodes.
>
> Still failing
>
> Destination:
>
> Slon log:
>
> 2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: 6525.754 seconds to
> copy table "cls"."listings"
> 2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: copy table
> "cls"."customers"
> 2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: Begin COPY of table
> "cls"."customers"
> 2012-12-10 12:04:49 PST ERROR  remoteWorkerThread_1: "select
> "_admissioncls".copyFields(8);"
> 2012-12-10 12:04:49 PST WARN   remoteWorkerThread_1: data copy for set 1
> failed 1 times - sleep 15 seconds
> 2012-12-10 12:04:51 PST INFO   cleanupThread: 5961.364 seconds for
> cleanupEvent()
> 2012-12-10 12:05:06 PST INFO   copy_set 1 - omit=f - bool=0
> 2012-12-10 12:05:06 PST INFO   omit is FALSE
> 2012-12-10 12:05:06 PST CONFIG version for "dbname=clsdb host=server
> user=postgres password=SECURED is 90104
> 2012-12-10 12:05:07 PST DEBUG1 copy_set_1 "dbname=clsdb host=server
> user=postgres password=SECURED": backend pid = 17092
> 2012-12-10 12:05:07 PST CONFIG remoteWorkerThread_1: connected to
> provider DB
>
> Postgres logs:
>
> 2012-12-10 12:04:51 PST admissionclsdb postgres [local] NOTICE:
> Slony-I: Logswitch to sl_log_2 initiated
> 2012-12-10 12:04:51 PST admissionclsdb postgres [local] CONTEXT:  SQL
> statement "SELECT "_admissioncls".logswitch_start()"
> 2012-12-10 12:05:12 PST admissionclsdb postgres [local] LOG:  sending
> cancel to blocking autovacuum PID 18620
> 2012-12-10 12:05:12 PST admissionclsdb postgres [local] DETAIL:  Process
> 18299 waits for AccessExclusiveLock on relation 17410 of database 16385.
> 2012-12-10 12:05:12 PST admissionclsdb postgres [local] STATEMENT:  lock
> table "cls"."listings";
> 2012-12-10 12:05:12 PST    ERROR:  canceling autovacuum task
> 2012-12-10 12:05:12 PST    CONTEXT:  automatic vacuum of table
> "admissionclsdb.cls.listings"
> 2012-12-10 12:05:12 PST admissionclsdb postgres [local] NOTICE:
> truncate of "cls"."autobodystyle" succeeded

What is the output of

     select > "_admissioncls".copyFields(8);

on node 1? It is important to do this on node 1 because that is where 
the remote worker, processing the copy_set, is doing this.


>
>
> Source:
>
> There is nothing in the slon log that would tell me it's aware of this
> client side restart or failure. Nothing in the postgres logs about an
> EOF or anything.
> Nothing in postgres log either that says there is an issue.

Please specify which postgres log you are talking about. There are at 
least two in this case, the one on the new node and the one on the data 
provider (node 1). The one from the data provider is where to expect any 
error messages.


Jan

-- 
Anyone who trades liberty for security deserves neither
liberty nor security. -- Benjamin Franklin

From drees76 at gmail.com  Mon Dec 10 15:05:28 2012
From: drees76 at gmail.com (David Rees)
Date: Mon, 10 Dec 2012 15:05:28 -0800
Subject: [Slony1-general] Multiple sets w/same table
In-Reply-To: <50C4CB5C.9060901@Yahoo.com>
References: <CAHtT9RuY9OYbRyE=D80f++RErqT+GpBc+byfDMzSH8bwiu=zzQ@mail.gmail.com>
	<BLU0-SMTP20818CE4A2C25BABF659562DC460@phx.gbl>
	<CAHtT9RsANTGpan9ovnF-Evfvur71hoGRMAOdrJAs39TY6FfrMw@mail.gmail.com>
	<50C124E0.7000409@ca.afilias.info> <50C4CB5C.9060901@Yahoo.com>
Message-ID: <CAHtT9RuaMvSBJxAGDeQc1h+Z-OyMOfUiK5PaBoak_wrnF-GPjw@mail.gmail.com>

On Sun, Dec 9, 2012 at 9:33 AM, Jan Wieck <JanWieck at yahoo.com> wrote:
> On 12/6/2012 6:06 PM, Steve Singer wrote:
>> On 12-12-04 11:50 PM, David Rees wrote:
>>> On Tue, Dec 4, 2012 at 7:34 PM, Steve Singer <steve at ssinger.info> wrote:
>>> For example, table 1 is in set 1 and table 2 is in set 2 and table 1
>>> has a foreign key that refers to table 2.
>>>
>>> Changes that occur on the origin node 1 which will be the same for set
>>> 1/2 will obviously be fine, but is it possible for an event to be
>>> committed out-of-order on node 2?
>>
>> If you subscribe  set 2 first, then set 1 and if both set 1 and your not
>> using a different forwarder node, then I think you should be okay.
>
> The subscriptions should work either way since it is done under
> session_replication_role=replica, which suppresses foreign key checks.

Thanks!  I'll give it a shot and see how it goes.

-Dave

From tmblue at gmail.com  Mon Dec 10 15:26:57 2012
From: tmblue at gmail.com (Tory M Blue)
Date: Mon, 10 Dec 2012 15:26:57 -0800
Subject: [Slony1-general] data copy for set 1 failed 3 times - sleep 60
	seconds
In-Reply-To: <50C66845.80006@Yahoo.com>
References: <CAEaSS0ZsK9inShCY9CR2X4fOwHeGzO7qGSmT2LbFmXsXy+R0yA@mail.gmail.com>
	<1354179426.14986.YahooMailNeo@web133202.mail.ir2.yahoo.com>
	<CAEaSS0aZi=zGZZADEDwVOM4nLRpP6C0cncCknyQBfJm8kTD+Ng@mail.gmail.com>
	<50B7A63B.3070804@ca.afilias.info>
	<CAEaSS0aLVWiDJ43dKjbfzq3Ldne2D07EQDEvTZrSVTpK84uFCg@mail.gmail.com>
	<50B7E03A.5040705@ca.afilias.info>
	<CAEaSS0apzgrdUv6ExkW3nf+TfQbcGQjvg32pvmY_q9QkQV3ATg@mail.gmail.com>
	<50B8C526.7090802@ca.afilias.info>
	<CAEaSS0bCWq+88mMnpt2+uzGK7-YuaOCW60WzupPiLuXR5QexnA@mail.gmail.com>
	<CAEaSS0aLOxufMA2eqG5du2Nfk4LfFRWGo22YvdTwP7EmjaYTzg@mail.gmail.com>
	<50C66845.80006@Yahoo.com>
Message-ID: <CAEaSS0bmU+SW-jWPt_t4j1kTPcoZtdO0USJJME9y25EpNxyWPg@mail.gmail.com>

On Mon, Dec 10, 2012 at 2:55 PM, Jan Wieck <JanWieck at yahoo.com> wrote:

> On 12/10/2012 5:28 PM, Tory M Blue wrote:
>
>>
>> I'm back to it with debug of 4 on the source and the destination nodes.
>>
>> Still failing
>>
>> Destination:
>>
>> Slon log:
>>
>> 2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: 6525.754 seconds to
>> copy table "cls"."listings"
>> 2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: copy table
>> "cls"."customers"
>> 2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: Begin COPY of table
>> "cls"."customers"
>> 2012-12-10 12:04:49 PST ERROR  remoteWorkerThread_1: "select
>> "_admissioncls".copyFields(8);**"
>> 2012-12-10 12:04:49 PST WARN   remoteWorkerThread_1: data copy for set 1
>> failed 1 times - sleep 15 seconds
>> 2012-12-10 12:04:51 PST INFO   cleanupThread: 5961.364 seconds for
>> cleanupEvent()
>> 2012-12-10 12:05:06 PST INFO   copy_set 1 - omit=f - bool=0
>> 2012-12-10 12:05:06 PST INFO   omit is FALSE
>> 2012-12-10 12:05:06 PST CONFIG version for "dbname=clsdb host=server
>> user=postgres password=SECURED is 90104
>> 2012-12-10 12:05:07 PST DEBUG1 copy_set_1 "dbname=clsdb host=server
>> user=postgres password=SECURED": backend pid = 17092
>> 2012-12-10 12:05:07 PST CONFIG remoteWorkerThread_1: connected to
>> provider DB
>>
>> Postgres logs:
>>
>> 2012-12-10 12:04:51 PST admissionclsdb postgres [local] NOTICE:
>> Slony-I: Logswitch to sl_log_2 initiated
>> 2012-12-10 12:04:51 PST admissionclsdb postgres [local] CONTEXT:  SQL
>> statement "SELECT "_admissioncls".logswitch_**start()"
>> 2012-12-10 12:05:12 PST admissionclsdb postgres [local] LOG:  sending
>> cancel to blocking autovacuum PID 18620
>> 2012-12-10 12:05:12 PST admissionclsdb postgres [local] DETAIL:  Process
>> 18299 waits for AccessExclusiveLock on relation 17410 of database 16385.
>> 2012-12-10 12:05:12 PST admissionclsdb postgres [local] STATEMENT:  lock
>> table "cls"."listings";
>> 2012-12-10 12:05:12 PST    ERROR:  canceling autovacuum task
>> 2012-12-10 12:05:12 PST    CONTEXT:  automatic vacuum of table
>> "admissionclsdb.cls.listings"
>> 2012-12-10 12:05:12 PST admissionclsdb postgres [local] NOTICE:
>> truncate of "cls"."autobodystyle" succeeded
>>
>
> What is the output of
>
>     select > "_admissioncls".copyFields(8);
>
> on node 1? It is important to do this on node 1 because that is where the
> remote worker, processing the copy_set, is doing this.
>
> On node 1? In my configuration that's the primary master, which this node
is not talking to. This node is talking to node 2 (our slave).

1->2 -> 10 (this offsite node)
1->3/4

But node 1

admissionclsdb=# select "_admissioncls".copyFields(8);



copyfields



--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
---------
 ("cust_seq_id","customer_id","customer_name","disabled","account","defa
ult_status","impression_credits","cost_fractional_cpm","acct_list","pricing_type
","pricing_model","subscription_price","monthly_price","monthly_minimum","accoun
t_type")
(1 row)


Node 2:
admissionclsdb=# select "_admissioncls".copyFields(8);



copyfields



--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
---------
 ("cust_seq_id","customer_id","customer_name","disabled","account","defa
ult_status","impression_credits","cost_fractional_cpm","acct_list","pricing_type
","pricing_model","subscription_price","monthly_price","monthly_minimum","accoun
t_type")
(1 row)

And note, on my larger table when I try to skip set 1 and just go to set 2,
that has a table that is 4x as large and the resulting  field number is 4,
vs the 8. So it's not this particular table. I can sync set 3 just fine
(but it's small, finishes within 30 minutes).



>>
>> Source:
>>
>> There is nothing in the slon log that would tell me it's aware of this
>> client side restart or failure. Nothing in the postgres logs about an
>> EOF or anything.
>> Nothing in postgres log either that says there is an issue.
>>
>
> Please specify which postgres log you are talking about. There are at
> least two in this case, the one on the new node and the one on the data
> provider (node 1). The one from the data provider is where to expect any
> error messages.


Sorry I was trying to be clear, with destination and source.

Source is node 2 , nothing in todays main postgresql log nor in the slon
log.
Destination is node 10, nothing in the postgresql log and I've posted the
bits from the slon log

Thanks for not giving up on me
Tory
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20121210/8b5ad45d/attachment-0001.htm 

From JanWieck at Yahoo.com  Mon Dec 10 15:59:05 2012
From: JanWieck at Yahoo.com (Jan Wieck)
Date: Mon, 10 Dec 2012 18:59:05 -0500
Subject: [Slony1-general] data copy for set 1 failed 3 times - sleep 60
 seconds
In-Reply-To: <CAEaSS0bmU+SW-jWPt_t4j1kTPcoZtdO0USJJME9y25EpNxyWPg@mail.gmail.com>
References: <CAEaSS0ZsK9inShCY9CR2X4fOwHeGzO7qGSmT2LbFmXsXy+R0yA@mail.gmail.com>
	<1354179426.14986.YahooMailNeo@web133202.mail.ir2.yahoo.com>
	<CAEaSS0aZi=zGZZADEDwVOM4nLRpP6C0cncCknyQBfJm8kTD+Ng@mail.gmail.com>
	<50B7A63B.3070804@ca.afilias.info>
	<CAEaSS0aLVWiDJ43dKjbfzq3Ldne2D07EQDEvTZrSVTpK84uFCg@mail.gmail.com>
	<50B7E03A.5040705@ca.afilias.info>
	<CAEaSS0apzgrdUv6ExkW3nf+TfQbcGQjvg32pvmY_q9QkQV3ATg@mail.gmail.com>
	<50B8C526.7090802@ca.afilias.info>
	<CAEaSS0bCWq+88mMnpt2+uzGK7-YuaOCW60WzupPiLuXR5QexnA@mail.gmail.com>
	<CAEaSS0aLOxufMA2eqG5du2Nfk4LfFRWGo22YvdTwP7EmjaYTzg@mail.gmail.com>
	<50C66845.80006@Yahoo.com>
	<CAEaSS0bmU+SW-jWPt_t4j1kTPcoZtdO0USJJME9y25EpNxyWPg@mail.gmail.com>
Message-ID: <50C67749.4080900@Yahoo.com>

On 12/10/2012 6:26 PM, Tory M Blue wrote:
>
>
> On Mon, Dec 10, 2012 at 2:55 PM, Jan Wieck <JanWieck at yahoo.com
> <mailto:JanWieck at yahoo.com>> wrote:
>
>     On 12/10/2012 5:28 PM, Tory M Blue wrote:
>
>
>         I'm back to it with debug of 4 on the source and the destination
>         nodes.
>
>         Still failing
>
>         Destination:
>
>         Slon log:
>
>         2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: 6525.754
>         seconds to
>         copy table "cls"."listings"
>         2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: copy table
>         "cls"."customers"
>         2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: Begin COPY
>         of table
>         "cls"."customers"
>         2012-12-10 12:04:49 PST ERROR  remoteWorkerThread_1: "select
>         "_admissioncls".copyFields(8);__"

This is the bit that I don't understand.

Looking at the remote_worker.c code, this error message comes from line 
3032 in 2.1 STABLE. The same code is in line 2911 in HEAD.

That select of copyFields() has apparently failed, because the result 
status code is not PGRES_TUPLES_OK, yet there seems to be nothing 
returned from PQresultErrorMessage().

I wonder what PQresStatus(PQresultStatus(res3)) as well as 
PQerrorMessage(pro_dbconn) at this point have to tell.


> Thanks for not giving up on me
> Tory

What version of Slony are you running this on?

Can you run a custom patched slon on the new subscriber so that we can 
see that information in the log?


Jan

-- 
Anyone who trades liberty for security deserves neither
liberty nor security. -- Benjamin Franklin

From tmblue at gmail.com  Mon Dec 10 16:09:05 2012
From: tmblue at gmail.com (Tory M Blue)
Date: Mon, 10 Dec 2012 16:09:05 -0800
Subject: [Slony1-general] data copy for set 1 failed 3 times - sleep 60
	seconds
In-Reply-To: <50C67749.4080900@Yahoo.com>
References: <CAEaSS0ZsK9inShCY9CR2X4fOwHeGzO7qGSmT2LbFmXsXy+R0yA@mail.gmail.com>
	<1354179426.14986.YahooMailNeo@web133202.mail.ir2.yahoo.com>
	<CAEaSS0aZi=zGZZADEDwVOM4nLRpP6C0cncCknyQBfJm8kTD+Ng@mail.gmail.com>
	<50B7A63B.3070804@ca.afilias.info>
	<CAEaSS0aLVWiDJ43dKjbfzq3Ldne2D07EQDEvTZrSVTpK84uFCg@mail.gmail.com>
	<50B7E03A.5040705@ca.afilias.info>
	<CAEaSS0apzgrdUv6ExkW3nf+TfQbcGQjvg32pvmY_q9QkQV3ATg@mail.gmail.com>
	<50B8C526.7090802@ca.afilias.info>
	<CAEaSS0bCWq+88mMnpt2+uzGK7-YuaOCW60WzupPiLuXR5QexnA@mail.gmail.com>
	<CAEaSS0aLOxufMA2eqG5du2Nfk4LfFRWGo22YvdTwP7EmjaYTzg@mail.gmail.com>
	<50C66845.80006@Yahoo.com>
	<CAEaSS0bmU+SW-jWPt_t4j1kTPcoZtdO0USJJME9y25EpNxyWPg@mail.gmail.com>
	<50C67749.4080900@Yahoo.com>
Message-ID: <CAEaSS0Y-H0VVJbG2KY9L2+UOEt6B5_1OCXNS18Wy-2nBRFTNtQ@mail.gmail.com>

On Mon, Dec 10, 2012 at 3:59 PM, Jan Wieck <JanWieck at yahoo.com> wrote:

> On 12/10/2012 6:26 PM, Tory M Blue wrote:
>
>>
>>
>> On Mon, Dec 10, 2012 at 2:55 PM, Jan Wieck <JanWieck at yahoo.com
>> <mailto:JanWieck at yahoo.com>> wrote:
>>
>>     On 12/10/2012 5:28 PM, Tory M Blue wrote:
>>
>>
>>         I'm back to it with debug of 4 on the source and the destination
>>         nodes.
>>
>>         Still failing
>>
>>         Destination:
>>
>>         Slon log:
>>
>>         2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: 6525.754
>>         seconds to
>>         copy table "cls"."listings"
>>         2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: copy table
>>         "cls"."customers"
>>         2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1: Begin COPY
>>         of table
>>         "cls"."customers"
>>         2012-12-10 12:04:49 PST ERROR  remoteWorkerThread_1: "select
>>         "_admissioncls".copyFields(8);**__"
>>
>
> This is the bit that I don't understand.
>
> Looking at the remote_worker.c code, this error message comes from line
> 3032 in 2.1 STABLE. The same code is in line 2911 in HEAD.
>
> That select of copyFields() has apparently failed, because the result
> status code is not PGRES_TUPLES_OK, yet there seems to be nothing returned
> from PQresultErrorMessage().
>
> I wonder what PQresStatus(PQresultStatus(**res3)) as well as
> PQerrorMessage(pro_dbconn) at this point have to tell.
>
>
>  Thanks for not giving up on me
>> Tory
>>
>
> What version of Slony are you running this on?
>

-bash-4.1$ slon -v
slon version 2.1.1

>
> Can you run a custom patched slon on the new subscriber so that we can see
> that information in the log?
>

Absolutely!

Thanks!
Tory
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20121210/53e78390/attachment.htm 

From JanWieck at Yahoo.com  Mon Dec 10 16:24:03 2012
From: JanWieck at Yahoo.com (Jan Wieck)
Date: Mon, 10 Dec 2012 19:24:03 -0500
Subject: [Slony1-general] data copy for set 1 failed 3 times - sleep 60
 seconds
In-Reply-To: <CAEaSS0Y-H0VVJbG2KY9L2+UOEt6B5_1OCXNS18Wy-2nBRFTNtQ@mail.gmail.com>
References: <CAEaSS0ZsK9inShCY9CR2X4fOwHeGzO7qGSmT2LbFmXsXy+R0yA@mail.gmail.com>
	<1354179426.14986.YahooMailNeo@web133202.mail.ir2.yahoo.com>
	<CAEaSS0aZi=zGZZADEDwVOM4nLRpP6C0cncCknyQBfJm8kTD+Ng@mail.gmail.com>
	<50B7A63B.3070804@ca.afilias.info>
	<CAEaSS0aLVWiDJ43dKjbfzq3Ldne2D07EQDEvTZrSVTpK84uFCg@mail.gmail.com>
	<50B7E03A.5040705@ca.afilias.info>
	<CAEaSS0apzgrdUv6ExkW3nf+TfQbcGQjvg32pvmY_q9QkQV3ATg@mail.gmail.com>
	<50B8C526.7090802@ca.afilias.info>
	<CAEaSS0bCWq+88mMnpt2+uzGK7-YuaOCW60WzupPiLuXR5QexnA@mail.gmail.com>
	<CAEaSS0aLOxufMA2eqG5du2Nfk4LfFRWGo22YvdTwP7EmjaYTzg@mail.gmail.com>
	<50C66845.80006@Yahoo.com>
	<CAEaSS0bmU+SW-jWPt_t4j1kTPcoZtdO0USJJME9y25EpNxyWPg@mail.gmail.com>
	<50C67749.4080900@Yahoo.com>
	<CAEaSS0Y-H0VVJbG2KY9L2+UOEt6B5_1OCXNS18Wy-2nBRFTNtQ@mail.gmail.com>
Message-ID: <50C67D23.3020205@Yahoo.com>

On 12/10/2012 7:09 PM, Tory M Blue wrote:
>
>
> On Mon, Dec 10, 2012 at 3:59 PM, Jan Wieck <JanWieck at yahoo.com
> <mailto:JanWieck at yahoo.com>> wrote:
>
>     On 12/10/2012 6:26 PM, Tory M Blue wrote:
>
>
>
>         On Mon, Dec 10, 2012 at 2:55 PM, Jan Wieck <JanWieck at yahoo.com
>         <mailto:JanWieck at yahoo.com>
>         <mailto:JanWieck at yahoo.com <mailto:JanWieck at yahoo.com>>> wrote:
>
>              On 12/10/2012 5:28 PM, Tory M Blue wrote:
>
>
>                  I'm back to it with debug of 4 on the source and the
>         destination
>                  nodes.
>
>                  Still failing
>
>                  Destination:
>
>                  Slon log:
>
>                  2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1:
>         6525.754
>                  seconds to
>                  copy table "cls"."listings"
>                  2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1:
>         copy table
>                  "cls"."customers"
>                  2012-12-10 12:04:49 PST CONFIG remoteWorkerThread_1:
>         Begin COPY
>                  of table
>                  "cls"."customers"
>                  2012-12-10 12:04:49 PST ERROR  remoteWorkerThread_1:
>         "select
>                  "_admissioncls".copyFields(8);____"
>
>
>     This is the bit that I don't understand.
>
>     Looking at the remote_worker.c code, this error message comes from
>     line 3032 in 2.1 STABLE. The same code is in line 2911 in HEAD.
>
>     That select of copyFields() has apparently failed, because the
>     result status code is not PGRES_TUPLES_OK, yet there seems to be
>     nothing returned from PQresultErrorMessage().
>
>     I wonder what PQresStatus(PQresultStatus(__res3)) as well as
>     PQerrorMessage(pro_dbconn) at this point have to tell.
>
>
>         Thanks for not giving up on me
>         Tory
>
>
>     What version of Slony are you running this on?
>
>
> -bash-4.1$ slon -v
> slon version 2.1.1
>
>
>     Can you run a custom patched slon on the new subscriber so that we
>     can see that information in the log?
>
>
> Absolutely!

Attached is a patch for 2.1.1 that adds that information to the error 
message. Since slon remains the same version, you only have to replace 
the slon binary on the new subscriber (node 10).


Jan

-- 
Anyone who trades liberty for security deserves neither
liberty nor security. -- Benjamin Franklin
-------------- next part --------------
A non-text attachment was scrubbed...
Name: Tory_M_Blue.1.diff
Type: text/x-patch
Size: 893 bytes
Desc: not available
Url : http://lists.slony.info/pipermail/slony1-general/attachments/20121210/0556a316/attachment.bin 

From sandeeptt at yahoo.com  Thu Dec 13 21:16:04 2012
From: sandeeptt at yahoo.com (Sandeep Thakkar)
Date: Thu, 13 Dec 2012 21:16:04 -0800 (PST)
Subject: [Slony1-general] Slony 2.1.2 versioning patch on Windows
Message-ID: <1355462164.4927.YahooMailNeo@web141401.mail.bf1.yahoo.com>

Hi

Slony-I 2.1.2 executables on Windows show the version as "2.1.1". Please find attached the patch.

Thanks?
Sandeep.
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20121213/c0630a60/attachment.htm 
-------------- next part --------------
A non-text attachment was scrubbed...
Name: slony_version_msvc_212.patch
Type: application/octet-stream
Size: 675 bytes
Desc: not available
Url : http://lists.slony.info/pipermail/slony1-general/attachments/20121213/c0630a60/attachment.obj 

From sandeep.thakkar at enterprisedb.com  Fri Dec 14 04:44:29 2012
From: sandeep.thakkar at enterprisedb.com (Sandeep Thakkar)
Date: Fri, 14 Dec 2012 18:14:29 +0530
Subject: [Slony1-general] Slony 2.1.2 versioning patch on Windows
Message-ID: <CANFyU96jWwOgKN-oVeE5n2s7u-+HET-+3OZYaHvnp5ATA2K7kA@mail.gmail.com>

Hi

Slony-I 2.1.2 executables on Windows show the version as "2.1.1". Please
find attached the patch to fix this.

-Sandeep
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20121214/5cc840c7/attachment.htm 
-------------- next part --------------
A non-text attachment was scrubbed...
Name: slony_version_msvc_212.patch
Type: application/octet-stream
Size: 674 bytes
Desc: not available
Url : http://lists.slony.info/pipermail/slony1-general/attachments/20121214/5cc840c7/attachment.obj 

From ssinger at ca.afilias.info  Fri Dec 14 06:39:31 2012
From: ssinger at ca.afilias.info (Steve Singer)
Date: Fri, 14 Dec 2012 09:39:31 -0500
Subject: [Slony1-general] Slony 2.1.2 versioning patch on Windows
In-Reply-To: <1355462164.4927.YahooMailNeo@web141401.mail.bf1.yahoo.com>
References: <1355462164.4927.YahooMailNeo@web141401.mail.bf1.yahoo.com>
Message-ID: <50CB3A23.7070305@ca.afilias.info>

On 12-12-14 12:16 AM, Sandeep Thakkar wrote:
> Hi
>
> Slony-I 2.1.2 executables on Windows show the version as "2.1.1". Please
> find attached the patch.
>

Thanks, someone else had reported this a few weeks ago.

http://git.postgresql.org/gitweb/?p=slony1-engine.git;a=commit;h=acc4dd794907f274c803b6b18b4c36a50899b30e



> Thanks
> Sandeep.
>
>
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general
>


From matthias at aic.at  Mon Dec 17 07:19:04 2012
From: matthias at aic.at (Matthias Leopold)
Date: Mon, 17 Dec 2012 16:19:04 +0100
Subject: [Slony1-general] Bug 111/slony 1.2.21
Message-ID: <50CF37E8.5040809@aic.at>

hi,

is there any - maybe "brute force" - solution available for the case 
described in http://www.slony.info/bugzilla/show_bug.cgi?id=111 ?

i have this situation right now and i don't want to fiddle with sl_* 
tables directly (without instructions).

thx
matthias

-- 
Mit freundlichen Gr?ssen

Matthias Leopold
System & Network Administration

Streams Telecommunicationsservices GmbH
Universitaetsstrasse 10/7, 1090 Vienna, Austria

tel: +43 1 40159113
fax: +43 1 40159300
------------------------------------------------

From matthias at aic.at  Mon Dec 17 11:34:43 2012
From: matthias at aic.at (Matthias Leopold)
Date: Mon, 17 Dec 2012 20:34:43 +0100
Subject: [Slony1-general] Bug 111/slony 1.2.21
In-Reply-To: <50CF37E8.5040809@aic.at>
References: <50CF37E8.5040809@aic.at>
Message-ID: <50CF73D3.2030706@aic.at>

Am 2012-12-17 16:19, schrieb Matthias Leopold:
> hi,
>
> is there any - maybe "brute force" - solution available for the case
> described in http://www.slony.info/bugzilla/show_bug.cgi?id=111 ?
>
> i have this situation right now and i don't want to fiddle with sl_*
> tables directly (without instructions).
>
> thx
> matthias
>

ok, one step further(?):

as soon as i noticed the above mentioned condition stops the WHOLE 
replication process for the affected nodes (although only triggered by a 
"move set" test for a test set...) i recreated the nodes from scratch.

now i'm "only" left with messages about "Events not propagating in 
sl_event" to a now non-existent node (recreated because of this with a 
new id). can someone tell me how to get rid of these (hopefully) 
harmless messages?

thx very much
matthias


-- 
Mit freundlichen Gr?ssen

Matthias Leopold
System & Network Administration

Streams Telecommunicationsservices GmbH
Universitaetsstrasse 10/7, 1090 Vienna, Austria

tel: +43 1 40159113
fax: +43 1 40159300
------------------------------------------------

