From mjames at profitpoint.com  Tue Oct  1 12:47:42 2013
From: mjames at profitpoint.com (Mike James)
Date: Tue, 1 Oct 2013 19:47:42 +0000
Subject: [Slony1-general] help with error
Message-ID: <CE709F1F.6609%mjames@profitpoint.com>

I just noticed this error in the pg log files. This particular old instance is running postgresql 8.3.9 and slony1 2.0.3 rc2. Any ideas where this error originates. Google wasn't helpful in this case. Can I ignore it?

function _snapcluster.shouldslonyvacuumtable(name, name) does not exist at character 9

Mike
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20131001/6ea44f54/attachment.htm 

From steve at ssinger.info  Tue Oct  1 12:58:03 2013
From: steve at ssinger.info (Steve Singer)
Date: Tue, 1 Oct 2013 15:58:03 -0400
Subject: [Slony1-general] help with error
In-Reply-To: <CE709F1F.6609%mjames@profitpoint.com>
References: <CE709F1F.6609%mjames@profitpoint.com>
Message-ID: <BLU0-SMTP48FDB838FF64D849906EEFDC150@phx.gbl>

On 10/01/2013 03:47 PM, Mike James wrote:
> I just noticed this error in the pg log files. This particular old
> instance is running postgresql 8.3.9 and slony1 2.0.3 rc2. Any ideas
> where this error originates. Google wasn't helpful in this case. Can I
> ignore it?
>
> function _snapcluster.shouldslonyvacuumtable(name, name) does not exist
> at character 9
>

This bug was fixed between 2.0.3 RC2 and the actual 2.0.3 
(e31daffec5968470072a1dd435e11d49e620111c I think)

Note that 2.0.3 ended up being a bad release, if your upgrading you 
should at *least* upgrade to 2.0.4


> Mike
>
>
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general
>


From mjames at profitpoint.com  Tue Oct  1 13:06:01 2013
From: mjames at profitpoint.com (Mike James)
Date: Tue, 1 Oct 2013 20:06:01 +0000
Subject: [Slony1-general] help with error
In-Reply-To: <BLU0-SMTP48FDB838FF64D849906EEFDC150@phx.gbl>
Message-ID: <CE70A2E8.6616%mjames@profitpoint.com>

Hmm, ok. We are migrating, however slowly, to postgresql 9.2 and the
corresponding slony1 package in the pgdg apt-get repo. I inherited this
dinosaur :)

Thanks for the quick response.

Mike 

On 10/1/13 3:58 PM, "Steve Singer" <steve at ssinger.info> wrote:

>On 10/01/2013 03:47 PM, Mike James wrote:
>> I just noticed this error in the pg log files. This particular old
>> instance is running postgresql 8.3.9 and slony1 2.0.3 rc2. Any ideas
>> where this error originates. Google wasn't helpful in this case. Can I
>> ignore it?
>>
>> function _snapcluster.shouldslonyvacuumtable(name, name) does not exist
>> at character 9
>>
>
>This bug was fixed between 2.0.3 RC2 and the actual 2.0.3
>(e31daffec5968470072a1dd435e11d49e620111c I think)
>
>Note that 2.0.3 ended up being a bad release, if your upgrading you
>should at *least* upgrade to 2.0.4
>
>
>> Mike
>>
>>
>> _______________________________________________
>> Slony1-general mailing list
>> Slony1-general at lists.slony.info
>> http://lists.slony.info/mailman/listinfo/slony1-general
>>
>


From cbbrowne at afilias.info  Thu Oct  3 08:38:44 2013
From: cbbrowne at afilias.info (Christopher Browne)
Date: Thu, 3 Oct 2013 11:38:44 -0400
Subject: [Slony1-general] MAXSTATEMENTS in src/parsestatements
Message-ID: <CANfbgbbNpGzNfa8rNuk3SR8NEsotH01wrYBG6LtChto36VY=Sw@mail.gmail.com>

An issue recently came up where someone was preparing a mighty large
EXECUTE SCRIPT request, and bumped up against the limit that the statement
parser statically determines that a script can have, at maximum,
MAXSTATEMENTS statements, and sets the value of that to 1000.

I'm responsible for having set that value; would like to debate it a little
bit.

The relevant data structure is that
   int STMTS[MAXSTATEMENTS]
is used to indicate where the end of each statement is within the script
being processed by EXECUTE SCRIPT.

I took the naive approach of declaring STMTS[] statically.  Seeing as how
we have had exactly one complaint about the matter since 2006, I rather
think that this was an appropriate choice.

It would be some effort to switch to allocate dynamically; I wonder if it
is apropos to:

a) Leave things alone, as there have been very few complaints over the last
7 years.

b) Increase the value from 1000 to something moderately larger, as people
likely tend to have more RAM these days.

c) Go to the effort of dynamic allocation, so that arbitrarily large
scripts are supportable.
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20131003/b46cfe1c/attachment.htm 

From smarchand at sgo.fr  Thu Oct 10 01:54:41 2013
From: smarchand at sgo.fr (Sebastien Marchand)
Date: Thu, 10 Oct 2013 10:54:41 +0200
Subject: [Slony1-general] slony 2.0.7 on postgresql 9.3
Message-ID: <003801cec596$5be93720$13bba560$@sgo.fr>

Hi everybody,

 

I would like to migrate my postgresql 9.0 to 9.3 but i have slony 2.0.7
installed

 

My question is : slony 2.0.7 can work on pg 9.3 ?

 

I tried to use pg_upgrade but i've got library error :/

 

My configuration : Centos 5.7 pg 9.0 slony 2.0.7 ( replication : 17 servers
)

 

Thanks a lot.

-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20131010/67fa31ed/attachment.htm 

From smarchand at sgo.fr  Wed Oct 16 05:29:53 2013
From: smarchand at sgo.fr (Sebastien Marchand)
Date: Wed, 16 Oct 2013 14:29:53 +0200
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
Message-ID: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>

Hi everybody,

 

I?ve got one replication server A schema A to server B schema B

No probleme that works

But i would like to do another replication in the same time, server B schema
B to server A schema A ( slony 2.0.7/pg 9.0 works )

I?ve got error :

Slony error :  <stdin>:55: waiting for event (101,5000000004) to be
confirmed on node 110

Pg error : < 2013-10-15 10:55:10.950 CEST >ERROR:  relation
"_sloncluster.sl_local_node_id" does not exist at character 30
< 2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from
"_sloncluster".sl_local_node_id

 

I need some help, thanks.

 

Cordialement, 

S?bastien Marchand

Soci?t? SGO

 

-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20131016/db1577cf/attachment.html 

From ssinger at ca.afilias.info  Wed Oct 16 06:06:47 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Wed, 16 Oct 2013 09:06:47 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
Message-ID: <525E8F67.202@ca.afilias.info>

On 10/16/2013 08:29 AM, Sebastien Marchand wrote:
> Hi everybody,

You need to be a lot more specific on what it is your doing/trying to do 
and how your going about doing it.

Slony normally replicates data from   schemaA.tableA on server 1 to
schemaA.tableA on server 2.



>
> I?ve got one replication server A schema A to server B schema B
>
> No probleme that works
>
> But i would like to do another replication in the same time, server B
> schema B to server A schema A ( slony 2.0.7/pg 9.0 works )
>
> I?ve got error :
>
> Slony error : <stdin>:55: waiting for event (101,5000000004) to be
> confirmed on node 110
>
> Pg error : < 2013-10-15 10:55:10.950 CEST >ERROR:  relation
> "_sloncluster.sl_local_node_id" does not exist at character 30
> < 2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from
> "_sloncluster".sl_local_node_id
>
> I need some help, thanks.
>
> Cordialement,
>
> S?bastien Marchand
>
> Soci?t? SGO
>
>
>
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general
>


From smarchand at sgo.fr  Wed Oct 16 06:17:01 2013
From: smarchand at sgo.fr (Sebastien Marchand)
Date: Wed, 16 Oct 2013 15:17:01 +0200
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <525E8F67.202@ca.afilias.info>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
Message-ID: <002b01ceca72$012f4280$038dc780$@sgo.fr>

Hi,

I want do this :

SERVER 1			SERVER 2
SCHEMA A	------->		SCHEMA A
SCHEMA B	<-------		SCHEMA B

That works in slony 2.0.7/pg 9.0

But with  slony 2.2 and postgresql 9.3 

SERVER 1			SERVER 2	
SCHEMA A	------->		SCHEMA A	=> OK
SCHEMA B	<-------		SCHEMA B	=> NOK

I've got this error 

<stdin>:55: waiting for event (101,5000000004) to be  confirmed on node 110

Pg error : 

2013-10-15 10:55:10.950 CEST >ERROR:  relation
"_sloncluster.sl_local_node_id" does not exist at character 30 
2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from
"_sloncluster".sl_local_node_id

Sorry for my english... :(

-----Message d'origine-----
De?: Steve Singer [mailto:ssinger at ca.afilias.info] 
Envoy??: mercredi 16 octobre 2013 15:07
??: Sebastien Marchand
Cc?: slony1-general at lists.slony.info
Objet?: Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication

On 10/16/2013 08:29 AM, Sebastien Marchand wrote:
> Hi everybody,

You need to be a lot more specific on what it is your doing/trying to do and
how your going about doing it.

Slony normally replicates data from   schemaA.tableA on server 1 to
schemaA.tableA on server 2.



>
> I?ve got one replication server A schema A to server B schema B
>
> No probleme that works
>
> But i would like to do another replication in the same time, server B 
> schema B to server A schema A ( slony 2.0.7/pg 9.0 works )
>
> I?ve got error :
>
> Slony error : <stdin>:55: waiting for event (101,5000000004) to be 
> confirmed on node 110
>
> Pg error : < 2013-10-15 10:55:10.950 CEST >ERROR:  relation 
> "_sloncluster.sl_local_node_id" does not exist at character 30 < 
> 2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from 
> "_sloncluster".sl_local_node_id
>
> I need some help, thanks.
>
> Cordialement,
>
> S?bastien Marchand
>
> Soci?t? SGO
>
>
>
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general
>


From ssinger at ca.afilias.info  Wed Oct 16 06:29:02 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Wed, 16 Oct 2013 09:29:02 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <002b01ceca72$012f4280$038dc780$@sgo.fr>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
Message-ID: <525E949E.5070804@ca.afilias.info>

On 10/16/2013 09:17 AM, Sebastien Marchand wrote:
> Hi,
>
> I want do this :
>
> SERVER 1			SERVER 2
> SCHEMA A	------->		SCHEMA A
> SCHEMA B	<-------		SCHEMA B
>
> That works in slony 2.0.7/pg 9.0
>
> But with  slony 2.2 and postgresql 9.3
>
> SERVER 1			SERVER 2	
> SCHEMA A	------->		SCHEMA A	=> OK
> SCHEMA B	<-------		SCHEMA B	=> NOK
>
> I've got this error
>
> <stdin>:55: waiting for event (101,5000000004) to be  confirmed on node 110
>
> Pg error :
>
> 2013-10-15 10:55:10.950 CEST >ERROR:  relation
> "_sloncluster.sl_local_node_id" does not exist at character 30
> 2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from
> "_sloncluster".sl_local_node_id
>
> Sorry for my english... :(
>

The way you would do this is with two replication sets

clustername=sloncluster;
node 1 admin conninfo=.....
node 2 admin conninfo=.....

init cluster(id=1);
store node(id=2, event node=2);
store path(server=1,client=2,conninfo=....);
store path(server=2,client=1,conninfo=.....);

create set(id=1,origin=1);
set add table(set id=1, tables='schemaA\.*');
create set(id=2, origin=2);
set add table(set id=1, tables='schemaB\.*');

subscribe set(set id=1, provider,1,receiver=2);
sync(id=1);
wait for event(origin=1, wait on=1,confirmed=2);
subscribe set(set id=2, provider=2,receiver=1);
sync(id=2);
wait for event(origin=2,wait on=2,confirmed=1);


or something similiar to above should work the same in 2.1 and 2.2  (in 
2.0 you would need explicit 'set add table' statements for each table 
and maybe a few more 'wait for event' statements in the middle of the 
script).

Are you doing something significantly different?




From smarchand at sgo.fr  Wed Oct 16 06:55:28 2013
From: smarchand at sgo.fr (Sebastien Marchand)
Date: Wed, 16 Oct 2013 15:55:28 +0200
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <525E949E.5070804@ca.afilias.info>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
Message-ID: <002c01ceca77$5f751270$1e5f3750$@sgo.fr>

Sorry I forgot to tell you that I have 2 differents replications .

> SERVER 1			SERVER 2
> SCHEMA A	------->		SCHEMA A  (CLUSTER NAME =
repli_general  )
> SCHEMA B	<-------		SCHEMA B   (CLUSTER NAME =
repli_local110 )

Now one script i use (slony-ctl ) :

#!/bin/bash
## EN: Slonik script for initialising replication
/usr/pgsql-9.3/bin/slonik <<_EOF_
    ## EN: Preamble file contains all useful connexions information
	
CLUSTER NAME = repli_local110 ;
NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432
user=slony password=password';
NODE 110 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.110 port=5432
user=slony password=password';

    #--
    # Init the first node.  This creates the schema _repli_local110 
    # containing all replication system specific database objects.
    #--
    try{
    	init cluster ( id=101, comment = 'repli_local110 : 101 - DATABASE -
192.168.0.101');
    }
    on error {
	echo 'Cluster 101 : ko' ;
	exit 1;
	}
    on success { echo 'Cluster 101 : OK' ; }

    # The other nodes.

   #--
   # Create the node 110 (slave) and tell the 2 nodes how to connect to
   # each other and how they should listen for events.
   #--

   try{
       store node (id = 110,
        EVENT NODE = 101,
        comment = 'DB DATABASE - Host 192.168.0.110 - Cluster
repli_local110');
    }
    on error {
	echo 'Store node 110 ko';
	exit 1;
	}
    on success {
	echo 'Store node 110 OK';
	}

    store path (server = 101, client = 110, conninfo='dbname=DATABASE
host=192.168.0.101 port=5432 user=slony password=123');

    store path (server = 110, client = 101, conninfo='dbname=DATABASE
host=192.168.0.110 port=5432 user=slony password=123');

	
    #--
    # Slony-I organizes tables into sets.  The smallest unit a node can
    # subscribe is a set. The master or origin of the set is node 110.
    #--
    try{
        create set (id=1, origin=110, comment='Tables in DATABASE');
	# Tables

		set add table (set id=1, origin=101, id=67, fully qualified
name = 'local110.test_tata2', comment='table local110.test_tata2');

	# Sequences
    }
    on error {
	echo 'Creation Set : ko';
	exit 1;
	}
    on success {
	echo 'Creation Set : OK';
	}
    exit 0;
_EOF_

if [ $? -ne 0 ]; then
    error "CREATE SET" 3
    exit 1
fi

## EN: We start daemons. All on the same machine, which is
# the one on which that script is executed.
/usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
repli_local110 "dbname=DATABASE host=192.168.0.101 port=5432 user=slony
password=123"
>/home/slony1-ctl/slony-ctl/logs/repli_local110_DATABASE_101.log 2>&1 &
echo "daemon slon pour DATABASE - 192.168.0.101 demarr?? sur national101"
ssh/usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
repli_local110 "dbname=DATABASE host=192.168.0.110 port=5432 user=slony
password=123" >/home/slony/logs/repli_local110_DATABASE_110.log 2>&1 &
echo "daemon slon pour DATABASE - 192.168.0.110 demarr?? sur national101"

## EN: And now, subscription

echo "Souscription Set 1 par 101"
/usr/pgsql-9.3/bin/slonik <<_EOF_
    # ----
    # <preamble> file 
    # ----
    INCLUDE </home/slony1-ctl/slony-ctl/etc/repli_local110.preamble>

    # ----
    # Node 101 subscribes set 1
    # ----
    try{
    	subscribe set ( id = 1, provider = 110, receiver = 101, forward =
yes);
    }
    on error {
	echo 'Souscription ko';
	exit 1;
	}
    on success {
	echo 'Souscription OK';
	}
_EOF_


if [ $? -ne 0 ]; then
    error "SUBSCRIBE SET" 3
    exit 1
fi
exit 0




-----Message d'origine-----
De?: Steve Singer [mailto:ssinger at ca.afilias.info] 
Envoy??: mercredi 16 octobre 2013 15:29
??: Sebastien Marchand
Cc?: slony1-general at lists.slony.info
Objet?: Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication

On 10/16/2013 09:17 AM, Sebastien Marchand wrote:
> Hi,
>
> I want do this :
>
> SERVER 1			SERVER 2
> SCHEMA A	------->		SCHEMA A
> SCHEMA B	<-------		SCHEMA B
>
> That works in slony 2.0.7/pg 9.0
>
> But with  slony 2.2 and postgresql 9.3
>
> SERVER 1			SERVER 2	
> SCHEMA A	------->		SCHEMA A	=> OK
> SCHEMA B	<-------		SCHEMA B	=> NOK
>
> I've got this error
>
> <stdin>:55: waiting for event (101,5000000004) to be  confirmed on 
> node 110
>
> Pg error :
>
> 2013-10-15 10:55:10.950 CEST >ERROR:  relation 
> "_sloncluster.sl_local_node_id" does not exist at character 30
> 2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from 
> "_sloncluster".sl_local_node_id
>
> Sorry for my english... :(
>

The way you would do this is with two replication sets

clustername=sloncluster;
node 1 admin conninfo=.....
node 2 admin conninfo=.....

init cluster(id=1);
store node(id=2, event node=2);
store path(server=1,client=2,conninfo=....);
store path(server=2,client=1,conninfo=.....);

create set(id=1,origin=1);
set add table(set id=1, tables='schemaA\.*'); create set(id=2, origin=2);
set add table(set id=1, tables='schemaB\.*');

subscribe set(set id=1, provider,1,receiver=2); sync(id=1); wait for
event(origin=1, wait on=1,confirmed=2); subscribe set(set id=2,
provider=2,receiver=1); sync(id=2); wait for event(origin=2,wait
on=2,confirmed=1);


or something similiar to above should work the same in 2.1 and 2.2  (in
2.0 you would need explicit 'set add table' statements for each table and
maybe a few more 'wait for event' statements in the middle of the script).

Are you doing something significantly different?




From ssinger at ca.afilias.info  Wed Oct 16 07:02:35 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Wed, 16 Oct 2013 10:02:35 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <002c01ceca77$5f751270$1e5f3750$@sgo.fr>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
Message-ID: <525E9C7B.4070300@ca.afilias.info>

On 10/16/2013 09:55 AM, Sebastien Marchand wrote:
> Sorry I forgot to tell you that I have 2 differents replications .
>
>> SERVER 1			SERVER 2
>> SCHEMA A	------->		SCHEMA A  (CLUSTER NAME =
> repli_general  )
>> SCHEMA B	<-------		SCHEMA B   (CLUSTER NAME =
> repli_local110 )
>
> Now one script i use (slony-ctl ) :


One of your scripts below references
INCLUDE </home/slony1-ctl/slony-ctl/etc/repli_local110.preamble>

but you don't include that file.

Since the error you pasted references "_sloncluster.sl_local_node_id"
not "repli_local110.sl_local_node_id"  I'm wondering if the error is 
that your setting the clustername to the wrong value?




>
> #!/bin/bash
> ## EN: Slonik script for initialising replication
> /usr/pgsql-9.3/bin/slonik <<_EOF_
>      ## EN: Preamble file contains all useful connexions information
> 	
> CLUSTER NAME = repli_local110 ;
> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432
> user=slony password=password';
> NODE 110 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.110 port=5432
> user=slony password=password';
>
>      #--
>      # Init the first node.  This creates the schema _repli_local110
>      # containing all replication system specific database objects.
>      #--
>      try{
>      	init cluster ( id=101, comment = 'repli_local110 : 101 - DATABASE -
> 192.168.0.101');
>      }
>      on error {
> 	echo 'Cluster 101 : ko' ;
> 	exit 1;
> 	}
>      on success { echo 'Cluster 101 : OK' ; }
>
>      # The other nodes.
>
>     #--
>     # Create the node 110 (slave) and tell the 2 nodes how to connect to
>     # each other and how they should listen for events.
>     #--
>
>     try{
>         store node (id = 110,
>          EVENT NODE = 101,
>          comment = 'DB DATABASE - Host 192.168.0.110 - Cluster
> repli_local110');
>      }
>      on error {
> 	echo 'Store node 110 ko';
> 	exit 1;
> 	}
>      on success {
> 	echo 'Store node 110 OK';
> 	}
>
>      store path (server = 101, client = 110, conninfo='dbname=DATABASE
> host=192.168.0.101 port=5432 user=slony password=123');
>
>      store path (server = 110, client = 101, conninfo='dbname=DATABASE
> host=192.168.0.110 port=5432 user=slony password=123');
>
> 	
>      #--
>      # Slony-I organizes tables into sets.  The smallest unit a node can
>      # subscribe is a set. The master or origin of the set is node 110.
>      #--
>      try{
>          create set (id=1, origin=110, comment='Tables in DATABASE');
> 	# Tables
>
> 		set add table (set id=1, origin=101, id=67, fully qualified
> name = 'local110.test_tata2', comment='table local110.test_tata2');
>
> 	# Sequences
>      }
>      on error {
> 	echo 'Creation Set : ko';
> 	exit 1;
> 	}
>      on success {
> 	echo 'Creation Set : OK';
> 	}
>      exit 0;
> _EOF_
>
> if [ $? -ne 0 ]; then
>      error "CREATE SET" 3
>      exit 1
> fi
>
> ## EN: We start daemons. All on the same machine, which is
> # the one on which that script is executed.
> /usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
> repli_local110 "dbname=DATABASE host=192.168.0.101 port=5432 user=slony
> password=123"
>> /home/slony1-ctl/slony-ctl/logs/repli_local110_DATABASE_101.log 2>&1 &
> echo "daemon slon pour DATABASE - 192.168.0.101 demarr?? sur national101"
> ssh/usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
> repli_local110 "dbname=DATABASE host=192.168.0.110 port=5432 user=slony
> password=123" >/home/slony/logs/repli_local110_DATABASE_110.log 2>&1 &
> echo "daemon slon pour DATABASE - 192.168.0.110 demarr?? sur national101"
>
> ## EN: And now, subscription
>
> echo "Souscription Set 1 par 101"
> /usr/pgsql-9.3/bin/slonik <<_EOF_
>      # ----
>      # <preamble> file
>      # ----
>      INCLUDE </home/slony1-ctl/slony-ctl/etc/repli_local110.preamble>
>
>      # ----
>      # Node 101 subscribes set 1
>      # ----
>      try{
>      	subscribe set ( id = 1, provider = 110, receiver = 101, forward =
> yes);
>      }
>      on error {
> 	echo 'Souscription ko';
> 	exit 1;
> 	}
>      on success {
> 	echo 'Souscription OK';
> 	}
> _EOF_
>
>
> if [ $? -ne 0 ]; then
>      error "SUBSCRIBE SET" 3
>      exit 1
> fi
> exit 0
>
>
>
>
> -----Message d'origine-----
> De : Steve Singer [mailto:ssinger at ca.afilias.info]
> Envoy? : mercredi 16 octobre 2013 15:29
> ? : Sebastien Marchand
> Cc : slony1-general at lists.slony.info
> Objet : Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
>
> On 10/16/2013 09:17 AM, Sebastien Marchand wrote:
>> Hi,
>>
>> I want do this :
>>
>> SERVER 1			SERVER 2
>> SCHEMA A	------->		SCHEMA A
>> SCHEMA B	<-------		SCHEMA B
>>
>> That works in slony 2.0.7/pg 9.0
>>
>> But with  slony 2.2 and postgresql 9.3
>>
>> SERVER 1			SERVER 2	
>> SCHEMA A	------->		SCHEMA A	=> OK
>> SCHEMA B	<-------		SCHEMA B	=> NOK
>>
>> I've got this error
>>
>> <stdin>:55: waiting for event (101,5000000004) to be  confirmed on
>> node 110
>>
>> Pg error :
>>
>> 2013-10-15 10:55:10.950 CEST >ERROR:  relation
>> "_sloncluster.sl_local_node_id" does not exist at character 30
>> 2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from
>> "_sloncluster".sl_local_node_id
>>
>> Sorry for my english... :(
>>
>
> The way you would do this is with two replication sets
>
> clustername=sloncluster;
> node 1 admin conninfo=.....
> node 2 admin conninfo=.....
>
> init cluster(id=1);
> store node(id=2, event node=2);
> store path(server=1,client=2,conninfo=....);
> store path(server=2,client=1,conninfo=.....);
>
> create set(id=1,origin=1);
> set add table(set id=1, tables='schemaA\.*'); create set(id=2, origin=2);
> set add table(set id=1, tables='schemaB\.*');
>
> subscribe set(set id=1, provider,1,receiver=2); sync(id=1); wait for
> event(origin=1, wait on=1,confirmed=2); subscribe set(set id=2,
> provider=2,receiver=1); sync(id=2); wait for event(origin=2,wait
> on=2,confirmed=1);
>
>
> or something similiar to above should work the same in 2.1 and 2.2  (in
> 2.0 you would need explicit 'set add table' statements for each table and
> maybe a few more 'wait for event' statements in the middle of the script).
>
> Are you doing something significantly different?
>
>
>


From smarchand at sgo.fr  Wed Oct 16 07:06:48 2013
From: smarchand at sgo.fr (Sebastien Marchand)
Date: Wed, 16 Oct 2013 16:06:48 +0200
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <525E9C7B.4070300@ca.afilias.info>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
	<525E9C7B.4070300@ca.afilias.info>
Message-ID: <002d01ceca78$f707c190$e51744b0$@sgo.fr>

> CLUSTER NAME = repli_local110 ;
> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432
> user=slony password=password';
> NODE 110 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.110 port=5432
> user=slony password=password';

It's the file repli_local110.preamble but for email i copy this file in my
script :)

-----Message d'origine-----
De?: Steve Singer [mailto:ssinger at ca.afilias.info] 
Envoy??: mercredi 16 octobre 2013 16:03
??: Sebastien Marchand
Cc?: slony1-general at lists.slony.info
Objet?: Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication

On 10/16/2013 09:55 AM, Sebastien Marchand wrote:
> Sorry I forgot to tell you that I have 2 differents replications .
>
>> SERVER 1			SERVER 2
>> SCHEMA A	------->		SCHEMA A  (CLUSTER NAME =
> repli_general  )
>> SCHEMA B	<-------		SCHEMA B   (CLUSTER NAME =
> repli_local110 )
>
> Now one script i use (slony-ctl ) :


One of your scripts below references
INCLUDE </home/slony1-ctl/slony-ctl/etc/repli_local110.preamble>

but you don't include that file.

Since the error you pasted references "_sloncluster.sl_local_node_id"
not "repli_local110.sl_local_node_id"  I'm wondering if the error is that
your setting the clustername to the wrong value?




>
> #!/bin/bash
> ## EN: Slonik script for initialising replication
> /usr/pgsql-9.3/bin/slonik <<_EOF_
>      ## EN: Preamble file contains all useful connexions information
> 	
> CLUSTER NAME = repli_local110 ;
> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432
> user=slony password=password';
> NODE 110 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.110 port=5432
> user=slony password=password';
>
>      #--
>      # Init the first node.  This creates the schema _repli_local110
>      # containing all replication system specific database objects.
>      #--
>      try{
>      	init cluster ( id=101, comment = 'repli_local110 : 101 - DATABASE -
> 192.168.0.101');
>      }
>      on error {
> 	echo 'Cluster 101 : ko' ;
> 	exit 1;
> 	}
>      on success { echo 'Cluster 101 : OK' ; }
>
>      # The other nodes.
>
>     #--
>     # Create the node 110 (slave) and tell the 2 nodes how to connect to
>     # each other and how they should listen for events.
>     #--
>
>     try{
>         store node (id = 110,
>          EVENT NODE = 101,
>          comment = 'DB DATABASE - Host 192.168.0.110 - Cluster
> repli_local110');
>      }
>      on error {
> 	echo 'Store node 110 ko';
> 	exit 1;
> 	}
>      on success {
> 	echo 'Store node 110 OK';
> 	}
>
>      store path (server = 101, client = 110, conninfo='dbname=DATABASE
> host=192.168.0.101 port=5432 user=slony password=123');
>
>      store path (server = 110, client = 101, conninfo='dbname=DATABASE
> host=192.168.0.110 port=5432 user=slony password=123');
>
> 	
>      #--
>      # Slony-I organizes tables into sets.  The smallest unit a node can
>      # subscribe is a set. The master or origin of the set is node 110.
>      #--
>      try{
>          create set (id=1, origin=110, comment='Tables in DATABASE');
> 	# Tables
>
> 		set add table (set id=1, origin=101, id=67, fully qualified
> name = 'local110.test_tata2', comment='table local110.test_tata2');
>
> 	# Sequences
>      }
>      on error {
> 	echo 'Creation Set : ko';
> 	exit 1;
> 	}
>      on success {
> 	echo 'Creation Set : OK';
> 	}
>      exit 0;
> _EOF_
>
> if [ $? -ne 0 ]; then
>      error "CREATE SET" 3
>      exit 1
> fi
>
> ## EN: We start daemons. All on the same machine, which is
> # the one on which that script is executed.
> /usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
> repli_local110 "dbname=DATABASE host=192.168.0.101 port=5432 user=slony
> password=123"
>> /home/slony1-ctl/slony-ctl/logs/repli_local110_DATABASE_101.log 2>&1 &
> echo "daemon slon pour DATABASE - 192.168.0.101 demarr?? sur national101"
> ssh/usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
> repli_local110 "dbname=DATABASE host=192.168.0.110 port=5432 user=slony
> password=123" >/home/slony/logs/repli_local110_DATABASE_110.log 2>&1 &
> echo "daemon slon pour DATABASE - 192.168.0.110 demarr?? sur national101"
>
> ## EN: And now, subscription
>
> echo "Souscription Set 1 par 101"
> /usr/pgsql-9.3/bin/slonik <<_EOF_
>      # ----
>      # <preamble> file
>      # ----
>      INCLUDE </home/slony1-ctl/slony-ctl/etc/repli_local110.preamble>
>
>      # ----
>      # Node 101 subscribes set 1
>      # ----
>      try{
>      	subscribe set ( id = 1, provider = 110, receiver = 101, forward =
> yes);
>      }
>      on error {
> 	echo 'Souscription ko';
> 	exit 1;
> 	}
>      on success {
> 	echo 'Souscription OK';
> 	}
> _EOF_
>
>
> if [ $? -ne 0 ]; then
>      error "SUBSCRIBE SET" 3
>      exit 1
> fi
> exit 0
>
>
>
>
> -----Message d'origine-----
> De : Steve Singer [mailto:ssinger at ca.afilias.info]
> Envoy? : mercredi 16 octobre 2013 15:29
> ? : Sebastien Marchand
> Cc : slony1-general at lists.slony.info
> Objet : Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double
replication
>
> On 10/16/2013 09:17 AM, Sebastien Marchand wrote:
>> Hi,
>>
>> I want do this :
>>
>> SERVER 1			SERVER 2
>> SCHEMA A	------->		SCHEMA A
>> SCHEMA B	<-------		SCHEMA B
>>
>> That works in slony 2.0.7/pg 9.0
>>
>> But with  slony 2.2 and postgresql 9.3
>>
>> SERVER 1			SERVER 2	
>> SCHEMA A	------->		SCHEMA A	=> OK
>> SCHEMA B	<-------		SCHEMA B	=> NOK
>>
>> I've got this error
>>
>> <stdin>:55: waiting for event (101,5000000004) to be  confirmed on
>> node 110
>>
>> Pg error :
>>
>> 2013-10-15 10:55:10.950 CEST >ERROR:  relation
>> "_sloncluster.sl_local_node_id" does not exist at character 30
>> 2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from
>> "_sloncluster".sl_local_node_id
>>
>> Sorry for my english... :(
>>
>
> The way you would do this is with two replication sets
>
> clustername=sloncluster;
> node 1 admin conninfo=.....
> node 2 admin conninfo=.....
>
> init cluster(id=1);
> store node(id=2, event node=2);
> store path(server=1,client=2,conninfo=....);
> store path(server=2,client=1,conninfo=.....);
>
> create set(id=1,origin=1);
> set add table(set id=1, tables='schemaA\.*'); create set(id=2, origin=2);
> set add table(set id=1, tables='schemaB\.*');
>
> subscribe set(set id=1, provider,1,receiver=2); sync(id=1); wait for
> event(origin=1, wait on=1,confirmed=2); subscribe set(set id=2,
> provider=2,receiver=1); sync(id=2); wait for event(origin=2,wait
> on=2,confirmed=1);
>
>
> or something similiar to above should work the same in 2.1 and 2.2  (in
> 2.0 you would need explicit 'set add table' statements for each table and
> maybe a few more 'wait for event' statements in the middle of the script).
>
> Are you doing something significantly different?
>
>
>


From JanWieck at Yahoo.com  Wed Oct 16 07:15:45 2013
From: JanWieck at Yahoo.com (Jan Wieck)
Date: Wed, 16 Oct 2013 10:15:45 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <002c01ceca77$5f751270$1e5f3750$@sgo.fr>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
Message-ID: <525E9F91.7090902@Yahoo.com>

On 10/16/2013 09:55 AM, Sebastien Marchand wrote:
> Sorry I forgot to tell you that I have 2 differents replications .
>
>> SERVER 1			SERVER 2
>> SCHEMA A	------->		SCHEMA A  (CLUSTER NAME =
> repli_general  )
>> SCHEMA B	<-------		SCHEMA B   (CLUSTER NAME =
> repli_local110 )

This does not require two clusters with 4 slon daemons. Like Steve 
already wrote you only need two sets.


Jan


>
> Now one script i use (slony-ctl ) :
>
> #!/bin/bash
> ## EN: Slonik script for initialising replication
> /usr/pgsql-9.3/bin/slonik <<_EOF_
>      ## EN: Preamble file contains all useful connexions information
> 	
> CLUSTER NAME = repli_local110 ;
> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432
> user=slony password=password';
> NODE 110 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.110 port=5432
> user=slony password=password';
>
>      #--
>      # Init the first node.  This creates the schema _repli_local110
>      # containing all replication system specific database objects.
>      #--
>      try{
>      	init cluster ( id=101, comment = 'repli_local110 : 101 - DATABASE -
> 192.168.0.101');
>      }
>      on error {
> 	echo 'Cluster 101 : ko' ;
> 	exit 1;
> 	}
>      on success { echo 'Cluster 101 : OK' ; }
>
>      # The other nodes.
>
>     #--
>     # Create the node 110 (slave) and tell the 2 nodes how to connect to
>     # each other and how they should listen for events.
>     #--
>
>     try{
>         store node (id = 110,
>          EVENT NODE = 101,
>          comment = 'DB DATABASE - Host 192.168.0.110 - Cluster
> repli_local110');
>      }
>      on error {
> 	echo 'Store node 110 ko';
> 	exit 1;
> 	}
>      on success {
> 	echo 'Store node 110 OK';
> 	}
>
>      store path (server = 101, client = 110, conninfo='dbname=DATABASE
> host=192.168.0.101 port=5432 user=slony password=123');
>
>      store path (server = 110, client = 101, conninfo='dbname=DATABASE
> host=192.168.0.110 port=5432 user=slony password=123');
>
> 	
>      #--
>      # Slony-I organizes tables into sets.  The smallest unit a node can
>      # subscribe is a set. The master or origin of the set is node 110.
>      #--
>      try{
>          create set (id=1, origin=110, comment='Tables in DATABASE');
> 	# Tables
>
> 		set add table (set id=1, origin=101, id=67, fully qualified
> name = 'local110.test_tata2', comment='table local110.test_tata2');
>
> 	# Sequences
>      }
>      on error {
> 	echo 'Creation Set : ko';
> 	exit 1;
> 	}
>      on success {
> 	echo 'Creation Set : OK';
> 	}
>      exit 0;
> _EOF_
>
> if [ $? -ne 0 ]; then
>      error "CREATE SET" 3
>      exit 1
> fi
>
> ## EN: We start daemons. All on the same machine, which is
> # the one on which that script is executed.
> /usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
> repli_local110 "dbname=DATABASE host=192.168.0.101 port=5432 user=slony
> password=123"
>>/home/slony1-ctl/slony-ctl/logs/repli_local110_DATABASE_101.log 2>&1 &
> echo "daemon slon pour DATABASE - 192.168.0.101 demarr?? sur national101"
> ssh/usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
> repli_local110 "dbname=DATABASE host=192.168.0.110 port=5432 user=slony
> password=123" >/home/slony/logs/repli_local110_DATABASE_110.log 2>&1 &
> echo "daemon slon pour DATABASE - 192.168.0.110 demarr?? sur national101"
>
> ## EN: And now, subscription
>
> echo "Souscription Set 1 par 101"
> /usr/pgsql-9.3/bin/slonik <<_EOF_
>      # ----
>      # <preamble> file
>      # ----
>      INCLUDE </home/slony1-ctl/slony-ctl/etc/repli_local110.preamble>
>
>      # ----
>      # Node 101 subscribes set 1
>      # ----
>      try{
>      	subscribe set ( id = 1, provider = 110, receiver = 101, forward =
> yes);
>      }
>      on error {
> 	echo 'Souscription ko';
> 	exit 1;
> 	}
>      on success {
> 	echo 'Souscription OK';
> 	}
> _EOF_
>
>
> if [ $? -ne 0 ]; then
>      error "SUBSCRIBE SET" 3
>      exit 1
> fi
> exit 0
>
>
>
>
> -----Message d'origine-----
> De : Steve Singer [mailto:ssinger at ca.afilias.info]
> Envoy? : mercredi 16 octobre 2013 15:29
> ? : Sebastien Marchand
> Cc : slony1-general at lists.slony.info
> Objet : Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
>
> On 10/16/2013 09:17 AM, Sebastien Marchand wrote:
>> Hi,
>>
>> I want do this :
>>
>> SERVER 1			SERVER 2
>> SCHEMA A	------->		SCHEMA A
>> SCHEMA B	<-------		SCHEMA B
>>
>> That works in slony 2.0.7/pg 9.0
>>
>> But with  slony 2.2 and postgresql 9.3
>>
>> SERVER 1			SERVER 2	
>> SCHEMA A	------->		SCHEMA A	=> OK
>> SCHEMA B	<-------		SCHEMA B	=> NOK
>>
>> I've got this error
>>
>> <stdin>:55: waiting for event (101,5000000004) to be  confirmed on
>> node 110
>>
>> Pg error :
>>
>> 2013-10-15 10:55:10.950 CEST >ERROR:  relation
>> "_sloncluster.sl_local_node_id" does not exist at character 30
>> 2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from
>> "_sloncluster".sl_local_node_id
>>
>> Sorry for my english... :(
>>
>
> The way you would do this is with two replication sets
>
> clustername=sloncluster;
> node 1 admin conninfo=.....
> node 2 admin conninfo=.....
>
> init cluster(id=1);
> store node(id=2, event node=2);
> store path(server=1,client=2,conninfo=....);
> store path(server=2,client=1,conninfo=.....);
>
> create set(id=1,origin=1);
> set add table(set id=1, tables='schemaA\.*'); create set(id=2, origin=2);
> set add table(set id=1, tables='schemaB\.*');
>
> subscribe set(set id=1, provider,1,receiver=2); sync(id=1); wait for
> event(origin=1, wait on=1,confirmed=2); subscribe set(set id=2,
> provider=2,receiver=1); sync(id=2); wait for event(origin=2,wait
> on=2,confirmed=1);
>
>
> or something similiar to above should work the same in 2.1 and 2.2  (in
> 2.0 you would need explicit 'set add table' statements for each table and
> maybe a few more 'wait for event' statements in the middle of the script).
>
> Are you doing something significantly different?
>
>
>
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general
>


-- 
Anyone who trades liberty for security deserves neither
liberty nor security. -- Benjamin Franklin

From ssinger at ca.afilias.info  Wed Oct 16 07:48:38 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Wed, 16 Oct 2013 10:48:38 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <002d01ceca78$f707c190$e51744b0$@sgo.fr>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
	<525E9C7B.4070300@ca.afilias.info>
	<002d01ceca78$f707c190$e51744b0$@sgo.fr>
Message-ID: <525EA746.2010508@ca.afilias.info>

On 10/16/2013 10:06 AM, Sebastien Marchand wrote:
>> CLUSTER NAME = repli_local110 ;
>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432
>> user=slony password=password';
>> NODE 110 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.110 port=5432
>> user=slony password=password';
>
> It's the file repli_local110.preamble but for email i copy this file in my
> script :)

Sometimes details are important.

Copy the preamble file inline into your script and it will work (like 
you did in your email)

I can reproduce your issue with the preamble moved to a different file. 
  This is a bug, it shouldn't be hard to fix, thanks for reporting it. 
  I suspect the fix will be included in 2.2.1 due in the next few weeks 
(since this has been a busy week for 2.2.0 bugs - ie #318 and #320).




>
> -----Message d'origine-----
> De : Steve Singer [mailto:ssinger at ca.afilias.info]
> Envoy? : mercredi 16 octobre 2013 16:03
> ? : Sebastien Marchand
> Cc : slony1-general at lists.slony.info
> Objet : Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
>
> On 10/16/2013 09:55 AM, Sebastien Marchand wrote:
>> Sorry I forgot to tell you that I have 2 differents replications .
>>
>>> SERVER 1			SERVER 2
>>> SCHEMA A	------->		SCHEMA A  (CLUSTER NAME =
>> repli_general  )
>>> SCHEMA B	<-------		SCHEMA B   (CLUSTER NAME =
>> repli_local110 )
>>
>> Now one script i use (slony-ctl ) :
>
>
> One of your scripts below references
> INCLUDE </home/slony1-ctl/slony-ctl/etc/repli_local110.preamble>
>
> but you don't include that file.
>
> Since the error you pasted references "_sloncluster.sl_local_node_id"
> not "repli_local110.sl_local_node_id"  I'm wondering if the error is that
> your setting the clustername to the wrong value?
>
>
>
>
>>
>> #!/bin/bash
>> ## EN: Slonik script for initialising replication
>> /usr/pgsql-9.3/bin/slonik <<_EOF_
>>       ## EN: Preamble file contains all useful connexions information
>> 	
>> CLUSTER NAME = repli_local110 ;
>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432
>> user=slony password=password';
>> NODE 110 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.110 port=5432
>> user=slony password=password';
>>
>>       #--
>>       # Init the first node.  This creates the schema _repli_local110
>>       # containing all replication system specific database objects.
>>       #--
>>       try{
>>       	init cluster ( id=101, comment = 'repli_local110 : 101 - DATABASE -
>> 192.168.0.101');
>>       }
>>       on error {
>> 	echo 'Cluster 101 : ko' ;
>> 	exit 1;
>> 	}
>>       on success { echo 'Cluster 101 : OK' ; }
>>
>>       # The other nodes.
>>
>>      #--
>>      # Create the node 110 (slave) and tell the 2 nodes how to connect to
>>      # each other and how they should listen for events.
>>      #--
>>
>>      try{
>>          store node (id = 110,
>>           EVENT NODE = 101,
>>           comment = 'DB DATABASE - Host 192.168.0.110 - Cluster
>> repli_local110');
>>       }
>>       on error {
>> 	echo 'Store node 110 ko';
>> 	exit 1;
>> 	}
>>       on success {
>> 	echo 'Store node 110 OK';
>> 	}
>>
>>       store path (server = 101, client = 110, conninfo='dbname=DATABASE
>> host=192.168.0.101 port=5432 user=slony password=123');
>>
>>       store path (server = 110, client = 101, conninfo='dbname=DATABASE
>> host=192.168.0.110 port=5432 user=slony password=123');
>>
>> 	
>>       #--
>>       # Slony-I organizes tables into sets.  The smallest unit a node can
>>       # subscribe is a set. The master or origin of the set is node 110.
>>       #--
>>       try{
>>           create set (id=1, origin=110, comment='Tables in DATABASE');
>> 	# Tables
>>
>> 		set add table (set id=1, origin=101, id=67, fully qualified
>> name = 'local110.test_tata2', comment='table local110.test_tata2');
>>
>> 	# Sequences
>>       }
>>       on error {
>> 	echo 'Creation Set : ko';
>> 	exit 1;
>> 	}
>>       on success {
>> 	echo 'Creation Set : OK';
>> 	}
>>       exit 0;
>> _EOF_
>>
>> if [ $? -ne 0 ]; then
>>       error "CREATE SET" 3
>>       exit 1
>> fi
>>
>> ## EN: We start daemons. All on the same machine, which is
>> # the one on which that script is executed.
>> /usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
>> repli_local110 "dbname=DATABASE host=192.168.0.101 port=5432 user=slony
>> password=123"
>>> /home/slony1-ctl/slony-ctl/logs/repli_local110_DATABASE_101.log 2>&1 &
>> echo "daemon slon pour DATABASE - 192.168.0.101 demarr?? sur national101"
>> ssh/usr/pgsql-9.3/bin/slon -f /home/slony1-ctl/slony-ctl/etc/slon.cfg
>> repli_local110 "dbname=DATABASE host=192.168.0.110 port=5432 user=slony
>> password=123" >/home/slony/logs/repli_local110_DATABASE_110.log 2>&1 &
>> echo "daemon slon pour DATABASE - 192.168.0.110 demarr?? sur national101"
>>
>> ## EN: And now, subscription
>>
>> echo "Souscription Set 1 par 101"
>> /usr/pgsql-9.3/bin/slonik <<_EOF_
>>       # ----
>>       # <preamble> file
>>       # ----
>>       INCLUDE </home/slony1-ctl/slony-ctl/etc/repli_local110.preamble>
>>
>>       # ----
>>       # Node 101 subscribes set 1
>>       # ----
>>       try{
>>       	subscribe set ( id = 1, provider = 110, receiver = 101, forward =
>> yes);
>>       }
>>       on error {
>> 	echo 'Souscription ko';
>> 	exit 1;
>> 	}
>>       on success {
>> 	echo 'Souscription OK';
>> 	}
>> _EOF_
>>
>>
>> if [ $? -ne 0 ]; then
>>       error "SUBSCRIBE SET" 3
>>       exit 1
>> fi
>> exit 0
>>
>>
>>
>>
>> -----Message d'origine-----
>> De : Steve Singer [mailto:ssinger at ca.afilias.info]
>> Envoy? : mercredi 16 octobre 2013 15:29
>> ? : Sebastien Marchand
>> Cc : slony1-general at lists.slony.info
>> Objet : Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double
> replication
>>
>> On 10/16/2013 09:17 AM, Sebastien Marchand wrote:
>>> Hi,
>>>
>>> I want do this :
>>>
>>> SERVER 1			SERVER 2
>>> SCHEMA A	------->		SCHEMA A
>>> SCHEMA B	<-------		SCHEMA B
>>>
>>> That works in slony 2.0.7/pg 9.0
>>>
>>> But with  slony 2.2 and postgresql 9.3
>>>
>>> SERVER 1			SERVER 2	
>>> SCHEMA A	------->		SCHEMA A	=> OK
>>> SCHEMA B	<-------		SCHEMA B	=> NOK
>>>
>>> I've got this error
>>>
>>> <stdin>:55: waiting for event (101,5000000004) to be  confirmed on
>>> node 110
>>>
>>> Pg error :
>>>
>>> 2013-10-15 10:55:10.950 CEST >ERROR:  relation
>>> "_sloncluster.sl_local_node_id" does not exist at character 30
>>> 2013-10-15 10:55:10.950 CEST >STATEMENT:  select last_value::int4 from
>>> "_sloncluster".sl_local_node_id
>>>
>>> Sorry for my english... :(
>>>
>>
>> The way you would do this is with two replication sets
>>
>> clustername=sloncluster;
>> node 1 admin conninfo=.....
>> node 2 admin conninfo=.....
>>
>> init cluster(id=1);
>> store node(id=2, event node=2);
>> store path(server=1,client=2,conninfo=....);
>> store path(server=2,client=1,conninfo=.....);
>>
>> create set(id=1,origin=1);
>> set add table(set id=1, tables='schemaA\.*'); create set(id=2, origin=2);
>> set add table(set id=1, tables='schemaB\.*');
>>
>> subscribe set(set id=1, provider,1,receiver=2); sync(id=1); wait for
>> event(origin=1, wait on=1,confirmed=2); subscribe set(set id=2,
>> provider=2,receiver=1); sync(id=2); wait for event(origin=2,wait
>> on=2,confirmed=1);
>>
>>
>> or something similiar to above should work the same in 2.1 and 2.2  (in
>> 2.0 you would need explicit 'set add table' statements for each table and
>> maybe a few more 'wait for event' statements in the middle of the script).
>>
>> Are you doing something significantly different?
>>
>>
>>
>


From ssinger at ca.afilias.info  Wed Oct 16 07:53:21 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Wed, 16 Oct 2013 10:53:21 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <525EA746.2010508@ca.afilias.info>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
	<525E9C7B.4070300@ca.afilias.info>
	<002d01ceca78$f707c190$e51744b0$@sgo.fr>
	<525EA746.2010508@ca.afilias.info>
Message-ID: <525EA861.9040101@ca.afilias.info>

On 10/16/2013 10:48 AM, Steve Singer wrote:
> On 10/16/2013 10:06 AM, Sebastien Marchand wrote:
>>> CLUSTER NAME = repli_local110 ;
>>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432
>>> user=slony password=password';
>>> NODE 110 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.110 port=5432
>>> user=slony password=password';
>>
>> It's the file repli_local110.preamble but for email i copy this file
>> in my
>> script :)
>

Actually IGNORE what I said below,
I hit send way too quickly before reviewing my output.

I am NOT yet able to reproduce this, but try pasting your preamble 
inline and see if it works.

I think I see the line of code that is generating the error you are 
seeing but I don't understand how/why it is substituting using 
_sloncluster  instead of repli_local10;




> Sometimes details are important.
>
> Copy the preamble file inline into your script and it will work (like
> you did in your email)
>
> I can reproduce your issue with the preamble moved to a different file.
>   This is a bug, it shouldn't be hard to fix, thanks for reporting it.
>   I suspect the fix will be included in 2.2.1 due in the next few weeks
> (since this has been a busy week for 2.2.0 bugs - ie #318 and #320).
>
>

From smarchand at sgo.fr  Wed Oct 16 07:57:26 2013
From: smarchand at sgo.fr (Sebastien Marchand)
Date: Wed, 16 Oct 2013 16:57:26 +0200
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <525EA861.9040101@ca.afilias.info>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
	<525E9C7B.4070300@ca.afilias.info>
	<002d01ceca78$f707c190$e51744b0$@sgo.fr>
	<525EA746.2010508@ca.afilias.info>
	<525EA861.9040101@ca.afilias.info>
Message-ID: <002e01ceca80$07853c80$168fb580$@sgo.fr>

I already tried to put in script but no change.

Can you tell me where is the line of code that is generating this error ?
it's a sql function ?

I continue to search i need this to migrate.

-----Message d'origine-----
De?: Steve Singer [mailto:ssinger at ca.afilias.info] 
Envoy??: mercredi 16 octobre 2013 16:53
??: Sebastien Marchand
Cc?: slony1-general at lists.slony.info
Objet?: Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication

On 10/16/2013 10:48 AM, Steve Singer wrote:
> On 10/16/2013 10:06 AM, Sebastien Marchand wrote:
>>> CLUSTER NAME = repli_local110 ;
>>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432 
>>> user=slony password=password'; NODE 110 ADMIN CONNINFO = 
>>> 'dbname=RPP2 host=192.168.0.110 port=5432 user=slony 
>>> password=password';
>>
>> It's the file repli_local110.preamble but for email i copy this file 
>> in my script :)
>

Actually IGNORE what I said below,
I hit send way too quickly before reviewing my output.

I am NOT yet able to reproduce this, but try pasting your preamble inline
and see if it works.

I think I see the line of code that is generating the error you are seeing
but I don't understand how/why it is substituting using _sloncluster
instead of repli_local10;




> Sometimes details are important.
>
> Copy the preamble file inline into your script and it will work (like 
> you did in your email)
>
> I can reproduce your issue with the preamble moved to a different file.
>   This is a bug, it shouldn't be hard to fix, thanks for reporting it.
>   I suspect the fix will be included in 2.2.1 due in the next few 
> weeks (since this has been a busy week for 2.2.0 bugs - ie #318 and #320).
>
>


From ssinger at ca.afilias.info  Wed Oct 16 08:01:35 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Wed, 16 Oct 2013 11:01:35 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <002e01ceca80$07853c80$168fb580$@sgo.fr>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
	<525E9C7B.4070300@ca.afilias.info>
	<002d01ceca78$f707c190$e51744b0$@sgo.fr>
	<525EA746.2010508@ca.afilias.info>
	<525EA861.9040101@ca.afilias.info>
	<002e01ceca80$07853c80$168fb580$@sgo.fr>
Message-ID: <525EAA4F.1040907@ca.afilias.info>

On 10/16/2013 10:57 AM, Sebastien Marchand wrote:
> I already tried to put in script but no change.
>
> Can you tell me where is the line of code that is generating this error ?
> it's a sql function ?
>
> I continue to search i need this to migrate.



	slon_mkquery(&query, "select max(ev_seqno) FROM \"_%s\".sl_event"
				 " , \"_%s\".sl_node "
				 " where ev_origin= "
				 "     (select last_value from \"_%s\".sl_local_node_id) "
				 " AND %s AND sl_node.no_id="
				 " ev_origin"
				 ,script->clustername, script->clustername,
				 script->clustername, event_filter);


In slonik.c


slonik_get_last_event_id(SlonikStmt * stmt,
						 SlonikScript * script,
						 const char *event_filter,
						 int64 **events)


Also, if you are planning on migrating from 2.0 to 2.2 with UPDATE 
FUNCTIONS you should be aware of bug #320


>
> -----Message d'origine-----
> De : Steve Singer [mailto:ssinger at ca.afilias.info]
> Envoy? : mercredi 16 octobre 2013 16:53
> ? : Sebastien Marchand
> Cc : slony1-general at lists.slony.info
> Objet : Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
>
> On 10/16/2013 10:48 AM, Steve Singer wrote:
>> On 10/16/2013 10:06 AM, Sebastien Marchand wrote:
>>>> CLUSTER NAME = repli_local110 ;
>>>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 port=5432
>>>> user=slony password=password'; NODE 110 ADMIN CONNINFO =
>>>> 'dbname=RPP2 host=192.168.0.110 port=5432 user=slony
>>>> password=password';
>>>
>>> It's the file repli_local110.preamble but for email i copy this file
>>> in my script :)
>>
>
> Actually IGNORE what I said below,
> I hit send way too quickly before reviewing my output.
>
> I am NOT yet able to reproduce this, but try pasting your preamble inline
> and see if it works.
>
> I think I see the line of code that is generating the error you are seeing
> but I don't understand how/why it is substituting using _sloncluster
> instead of repli_local10;
>
>
>
>
>> Sometimes details are important.
>>
>> Copy the preamble file inline into your script and it will work (like
>> you did in your email)
>>
>> I can reproduce your issue with the preamble moved to a different file.
>>    This is a bug, it shouldn't be hard to fix, thanks for reporting it.
>>    I suspect the fix will be included in 2.2.1 due in the next few
>> weeks (since this has been a busy week for 2.2.0 bugs - ie #318 and #320).
>>
>>
>


From smarchand at sgo.fr  Wed Oct 16 09:05:44 2013
From: smarchand at sgo.fr (Sebastien Marchand)
Date: Wed, 16 Oct 2013 18:05:44 +0200
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <525EB71C.3000504@ca.afilias.info>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
	<525E9C7B.4070300@ca.afilias.info>
	<002d01ceca78$f707c190$e51744b0$@sgo.fr>
	<525EA746.2010508@ca.afilias.info>
	<525EA861.9040101@ca.afilias.info>
	<002e01ceca80$07853c80$168fb580$@sgo.fr>
	<525EAA4F.1040907@ca.afilias.info>
	<002f01ceca87$ad753b20$085fb160$@sgo.fr>
	<525EB71C.3000504@ca.afilias.info>
Message-ID: <003001ceca89$920478e0$b60d6aa0$@sgo.fr>

No slon running because script launch slon after create set.

So i launch before and IT WORKS !!! thx master ! thanks you so much

I don't know what it change in slony 2.0.7 and 2.2 but before i could do
this

But now it's ok :)

-----Message d'origine-----
De?: Steve Singer [mailto:ssinger at ca.afilias.info] 
Envoy??: mercredi 16 octobre 2013 17:56
??: Sebastien Marchand
Objet?: Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication

On 10/16/2013 11:52 AM, Sebastien Marchand wrote:
> Yes that's why i will delete all replication 2.0 and migrate 
> postgresql after i rebuild new replication.
>
> when i've my  error  " waiting for event (1,5000000004) to be 
> confirmed on node 110 " in postgresql if i do :
>
> select  * from _repli_local110.sl_path; => 1;110;"dbname=RPP2 
> host=192.168.0.101 port=5432 user=slony
> password=123";10
>
> Why just one line ?? i need two lines !
>
> In my sl_event :
>
> 110;5000000001;"2013-10-16
> 17:50:54.697374+02";"695958:695958:";"STORE_PATH";"1";"110";"dbname=RP
> P2
> host=192.168.0.101 port=5432 user=slony password=123";"10";"";"";"";""
>
> I think there is a problem here... or not

Slonik when it executes the STORE PATH , it will insert a row in sl_path on
each node.

When slon is running it will then replicate the STORE_PATH event from one
node to the other to create the second sl_path row in each node.

Is your slon running?


>
> -----Message d'origine-----
> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi 
> 16 octobre 2013 17:02 ? : Sebastien Marchand Cc : 
> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem 
> slony 2.2 and pg 9.3 double replication
>
> On 10/16/2013 10:57 AM, Sebastien Marchand wrote:
>> I already tried to put in script but no change.
>>
>> Can you tell me where is the line of code that is generating this error ?
>> it's a sql function ?
>>
>> I continue to search i need this to migrate.
>
>
>
> 	slon_mkquery(&query, "select max(ev_seqno) FROM \"_%s\".sl_event"
> 				 " , \"_%s\".sl_node "
> 				 " where ev_origin= "
> 				 "     (select last_value from
> \"_%s\".sl_local_node_id) "
> 				 " AND %s AND sl_node.no_id="
> 				 " ev_origin"
> 				 ,script->clustername, script->clustername,
> 				 script->clustername, event_filter);
>
>
> In slonik.c
>
>
> slonik_get_last_event_id(SlonikStmt * stmt,
> 						 SlonikScript * script,
> 						 const char *event_filter,
> 						 int64 **events)
>
>
> Also, if you are planning on migrating from 2.0 to 2.2 with UPDATE 
> FUNCTIONS you should be aware of bug #320
>
>
>>
>> -----Message d'origine-----
>> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi 
>> 16 octobre 2013 16:53 ? : Sebastien Marchand Cc : 
>> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem 
>> slony 2.2 and pg 9.3 double
> replication
>>
>> On 10/16/2013 10:48 AM, Steve Singer wrote:
>>> On 10/16/2013 10:06 AM, Sebastien Marchand wrote:
>>>>> CLUSTER NAME = repli_local110 ;
>>>>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101 
>>>>> port=5432 user=slony password=password'; NODE 110 ADMIN CONNINFO =
>>>>> 'dbname=RPP2 host=192.168.0.110 port=5432 user=slony 
>>>>> password=password';
>>>>
>>>> It's the file repli_local110.preamble but for email i copy this 
>>>> file in my script :)
>>>
>>
>> Actually IGNORE what I said below,
>> I hit send way too quickly before reviewing my output.
>>
>> I am NOT yet able to reproduce this, but try pasting your preamble 
>> inline and see if it works.
>>
>> I think I see the line of code that is generating the error you are 
>> seeing but I don't understand how/why it is substituting using 
>> _sloncluster instead of repli_local10;
>>
>>
>>
>>
>>> Sometimes details are important.
>>>
>>> Copy the preamble file inline into your script and it will work 
>>> (like you did in your email)
>>>
>>> I can reproduce your issue with the preamble moved to a different file.
>>>     This is a bug, it shouldn't be hard to fix, thanks for reporting it.
>>>     I suspect the fix will be included in 2.2.1 due in the next few 
>>> weeks (since this has been a busy week for 2.2.0 bugs - ie #318 and
> #320).
>>>
>>>
>>
>


From ssinger at ca.afilias.info  Wed Oct 16 10:33:30 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Wed, 16 Oct 2013 13:33:30 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <003001ceca89$920478e0$b60d6aa0$@sgo.fr>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
	<525E9C7B.4070300@ca.afilias.info>
	<002d01ceca78$f707c190$e51744b0$@sgo.fr>
	<525EA746.2010508@ca.afilias.info>
	<525EA861.9040101@ca.afilias.info>
	<002e01ceca80$07853c80$168fb580$@sgo.fr>
	<525EAA4F.1040907@ca.afilias.info>
	<002f01ceca87$ad753b20$085fb160$@sgo.fr>
	<525EB71C.3000504@ca.afilias.info>
	<003001ceca89$920478e0$b60d6aa0$@sgo.fr>
Message-ID: <525ECDEA.8070102@ca.afilias.info>

On 10/16/2013 12:05 PM, Sebastien Marchand wrote:
> No slon running because script launch slon after create set.
>
> So i launch before and IT WORKS !!! thx master ! thanks you so much
>
> I don't know what it change in slony 2.0.7 and 2.2 but before i could do
> this
>
> But now it's ok :)
>


What SHOULD happen with 2.2 when the slon isn't running is that slonik 
should keep printing:

waiting for event (1,5000000004) ...

messages, that isn't an error that is an information message saying that 
it is waiting for the event to be propogated, and that won't happen 
unless slonik is running.

What I don't understand is how you were getting

2013-10-15 10:55:10.950 CEST >ERROR:  relation
"_sloncluster.sl_local_node_id" does not exist at character 30


type messages.

> -----Message d'origine-----
> De : Steve Singer [mailto:ssinger at ca.afilias.info]
> Envoy? : mercredi 16 octobre 2013 17:56
> ? : Sebastien Marchand
> Objet : Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
>
> On 10/16/2013 11:52 AM, Sebastien Marchand wrote:
>> Yes that's why i will delete all replication 2.0 and migrate
>> postgresql after i rebuild new replication.
>>
>> when i've my  error  " waiting for event (1,5000000004) to be
>> confirmed on node 110 " in postgresql if i do :
>>
>> select  * from _repli_local110.sl_path; => 1;110;"dbname=RPP2
>> host=192.168.0.101 port=5432 user=slony
>> password=123";10
>>
>> Why just one line ?? i need two lines !
>>
>> In my sl_event :
>>
>> 110;5000000001;"2013-10-16
>> 17:50:54.697374+02";"695958:695958:";"STORE_PATH";"1";"110";"dbname=RP
>> P2
>> host=192.168.0.101 port=5432 user=slony password=123";"10";"";"";"";""
>>
>> I think there is a problem here... or not
>
> Slonik when it executes the STORE PATH , it will insert a row in sl_path on
> each node.
>
> When slon is running it will then replicate the STORE_PATH event from one
> node to the other to create the second sl_path row in each node.
>
> Is your slon running?
>
>
>>
>> -----Message d'origine-----
>> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi
>> 16 octobre 2013 17:02 ? : Sebastien Marchand Cc :
>> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem
>> slony 2.2 and pg 9.3 double replication
>>
>> On 10/16/2013 10:57 AM, Sebastien Marchand wrote:
>>> I already tried to put in script but no change.
>>>
>>> Can you tell me where is the line of code that is generating this error ?
>>> it's a sql function ?
>>>
>>> I continue to search i need this to migrate.
>>
>>
>>
>> 	slon_mkquery(&query, "select max(ev_seqno) FROM \"_%s\".sl_event"
>> 				 " , \"_%s\".sl_node "
>> 				 " where ev_origin= "
>> 				 "     (select last_value from
>> \"_%s\".sl_local_node_id) "
>> 				 " AND %s AND sl_node.no_id="
>> 				 " ev_origin"
>> 				 ,script->clustername, script->clustername,
>> 				 script->clustername, event_filter);
>>
>>
>> In slonik.c
>>
>>
>> slonik_get_last_event_id(SlonikStmt * stmt,
>> 						 SlonikScript * script,
>> 						 const char *event_filter,
>> 						 int64 **events)
>>
>>
>> Also, if you are planning on migrating from 2.0 to 2.2 with UPDATE
>> FUNCTIONS you should be aware of bug #320
>>
>>
>>>
>>> -----Message d'origine-----
>>> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi
>>> 16 octobre 2013 16:53 ? : Sebastien Marchand Cc :
>>> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem
>>> slony 2.2 and pg 9.3 double
>> replication
>>>
>>> On 10/16/2013 10:48 AM, Steve Singer wrote:
>>>> On 10/16/2013 10:06 AM, Sebastien Marchand wrote:
>>>>>> CLUSTER NAME = repli_local110 ;
>>>>>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101
>>>>>> port=5432 user=slony password=password'; NODE 110 ADMIN CONNINFO =
>>>>>> 'dbname=RPP2 host=192.168.0.110 port=5432 user=slony
>>>>>> password=password';
>>>>>
>>>>> It's the file repli_local110.preamble but for email i copy this
>>>>> file in my script :)
>>>>
>>>
>>> Actually IGNORE what I said below,
>>> I hit send way too quickly before reviewing my output.
>>>
>>> I am NOT yet able to reproduce this, but try pasting your preamble
>>> inline and see if it works.
>>>
>>> I think I see the line of code that is generating the error you are
>>> seeing but I don't understand how/why it is substituting using
>>> _sloncluster instead of repli_local10;
>>>
>>>
>>>
>>>
>>>> Sometimes details are important.
>>>>
>>>> Copy the preamble file inline into your script and it will work
>>>> (like you did in your email)
>>>>
>>>> I can reproduce your issue with the preamble moved to a different file.
>>>>      This is a bug, it shouldn't be hard to fix, thanks for reporting it.
>>>>      I suspect the fix will be included in 2.2.1 due in the next few
>>>> weeks (since this has been a busy week for 2.2.0 bugs - ie #318 and
>> #320).
>>>>
>>>>
>>>
>>
>


From JanWieck at Yahoo.com  Wed Oct 16 11:35:47 2013
From: JanWieck at Yahoo.com (Jan Wieck)
Date: Wed, 16 Oct 2013 14:35:47 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <525ECDEA.8070102@ca.afilias.info>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>	<525E8F67.202@ca.afilias.info>	<002b01ceca72$012f4280$038dc780$@sgo.fr>	<525E949E.5070804@ca.afilias.info>	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>	<525E9C7B.4070300@ca.afilias.info>	<002d01ceca78$f707c190$e51744b0$@sgo.fr>	<525EA746.2010508@ca.afilias.info>	<525EA861.9040101@ca.afilias.info>	<002e01ceca80$07853c80$168fb580$@sgo.fr>	<525EAA4F.1040907@ca.afilias.info>	<002f01ceca87$ad753b20$085fb160$@sgo.fr>	<525EB71C.3000504@ca.afilias.info>	<003001ceca89$920478e0$b60d6aa0$@sgo.fr>
	<525ECDEA.8070102@ca.afilias.info>
Message-ID: <525EDC83.9050504@Yahoo.com>

On 10/16/13 13:33, Steve Singer wrote:
> On 10/16/2013 12:05 PM, Sebastien Marchand wrote:
>> No slon running because script launch slon after create set.
>>
>> So i launch before and IT WORKS !!! thx master ! thanks you so much
>>
>> I don't know what it change in slony 2.0.7 and 2.2 but before i could do
>> this
>>
>> But now it's ok :)
>>
> 
> 
> What SHOULD happen with 2.2 when the slon isn't running is that slonik 
> should keep printing:
> 
> waiting for event (1,5000000004) ...
> 
> messages, that isn't an error that is an information message saying that 
> it is waiting for the event to be propogated, and that won't happen 
> unless slonik is running.
> 
> What I don't understand is how you were getting
> 
> 2013-10-15 10:55:10.950 CEST >ERROR:  relation
> "_sloncluster.sl_local_node_id" does not exist at character 30
> 
> 
> type messages.

That is not a slonik message, but is coming from slon. And sloncluster
is the cluster name used in share/slon.conf-sample.


Jan


> 
>> -----Message d'origine-----
>> De : Steve Singer [mailto:ssinger at ca.afilias.info]
>> Envoy? : mercredi 16 octobre 2013 17:56
>> ? : Sebastien Marchand
>> Objet : Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
>>
>> On 10/16/2013 11:52 AM, Sebastien Marchand wrote:
>>> Yes that's why i will delete all replication 2.0 and migrate
>>> postgresql after i rebuild new replication.
>>>
>>> when i've my  error  " waiting for event (1,5000000004) to be
>>> confirmed on node 110 " in postgresql if i do :
>>>
>>> select  * from _repli_local110.sl_path; => 1;110;"dbname=RPP2
>>> host=192.168.0.101 port=5432 user=slony
>>> password=123";10
>>>
>>> Why just one line ?? i need two lines !
>>>
>>> In my sl_event :
>>>
>>> 110;5000000001;"2013-10-16
>>> 17:50:54.697374+02";"695958:695958:";"STORE_PATH";"1";"110";"dbname=RP
>>> P2
>>> host=192.168.0.101 port=5432 user=slony password=123";"10";"";"";"";""
>>>
>>> I think there is a problem here... or not
>>
>> Slonik when it executes the STORE PATH , it will insert a row in sl_path on
>> each node.
>>
>> When slon is running it will then replicate the STORE_PATH event from one
>> node to the other to create the second sl_path row in each node.
>>
>> Is your slon running?
>>
>>
>>>
>>> -----Message d'origine-----
>>> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi
>>> 16 octobre 2013 17:02 ? : Sebastien Marchand Cc :
>>> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem
>>> slony 2.2 and pg 9.3 double replication
>>>
>>> On 10/16/2013 10:57 AM, Sebastien Marchand wrote:
>>>> I already tried to put in script but no change.
>>>>
>>>> Can you tell me where is the line of code that is generating this error ?
>>>> it's a sql function ?
>>>>
>>>> I continue to search i need this to migrate.
>>>
>>>
>>>
>>> 	slon_mkquery(&query, "select max(ev_seqno) FROM \"_%s\".sl_event"
>>> 				 " , \"_%s\".sl_node "
>>> 				 " where ev_origin= "
>>> 				 "     (select last_value from
>>> \"_%s\".sl_local_node_id) "
>>> 				 " AND %s AND sl_node.no_id="
>>> 				 " ev_origin"
>>> 				 ,script->clustername, script->clustername,
>>> 				 script->clustername, event_filter);
>>>
>>>
>>> In slonik.c
>>>
>>>
>>> slonik_get_last_event_id(SlonikStmt * stmt,
>>> 						 SlonikScript * script,
>>> 						 const char *event_filter,
>>> 						 int64 **events)
>>>
>>>
>>> Also, if you are planning on migrating from 2.0 to 2.2 with UPDATE
>>> FUNCTIONS you should be aware of bug #320
>>>
>>>
>>>>
>>>> -----Message d'origine-----
>>>> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi
>>>> 16 octobre 2013 16:53 ? : Sebastien Marchand Cc :
>>>> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem
>>>> slony 2.2 and pg 9.3 double
>>> replication
>>>>
>>>> On 10/16/2013 10:48 AM, Steve Singer wrote:
>>>>> On 10/16/2013 10:06 AM, Sebastien Marchand wrote:
>>>>>>> CLUSTER NAME = repli_local110 ;
>>>>>>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101
>>>>>>> port=5432 user=slony password=password'; NODE 110 ADMIN CONNINFO =
>>>>>>> 'dbname=RPP2 host=192.168.0.110 port=5432 user=slony
>>>>>>> password=password';
>>>>>>
>>>>>> It's the file repli_local110.preamble but for email i copy this
>>>>>> file in my script :)
>>>>>
>>>>
>>>> Actually IGNORE what I said below,
>>>> I hit send way too quickly before reviewing my output.
>>>>
>>>> I am NOT yet able to reproduce this, but try pasting your preamble
>>>> inline and see if it works.
>>>>
>>>> I think I see the line of code that is generating the error you are
>>>> seeing but I don't understand how/why it is substituting using
>>>> _sloncluster instead of repli_local10;
>>>>
>>>>
>>>>
>>>>
>>>>> Sometimes details are important.
>>>>>
>>>>> Copy the preamble file inline into your script and it will work
>>>>> (like you did in your email)
>>>>>
>>>>> I can reproduce your issue with the preamble moved to a different file.
>>>>>      This is a bug, it shouldn't be hard to fix, thanks for reporting it.
>>>>>      I suspect the fix will be included in 2.2.1 due in the next few
>>>>> weeks (since this has been a busy week for 2.2.0 bugs - ie #318 and
>>> #320).
>>>>>
>>>>>
>>>>
>>>
>>
> 
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general
> 


-- 
Anyone who trades liberty for security deserves neither
liberty nor security. -- Benjamin Franklin

From smarchand at sgo.fr  Thu Oct 17 02:08:14 2013
From: smarchand at sgo.fr (Sebastien Marchand)
Date: Thu, 17 Oct 2013 11:08:14 +0200
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <525ECDEA.8070102@ca.afilias.info>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
	<525E9C7B.4070300@ca.afilias.info>
	<002d01ceca78$f707c190$e51744b0$@sgo.fr>
	<525EA746.2010508@ca.afilias.info>
	<525EA861.9040101@ca.afilias.info>
	<002e01ceca80$07853c80$168fb580$@sgo.fr>
	<525EAA4F.1040907@ca.afilias.info>
	<002f01ceca87$ad753b20$085fb160$@sgo.fr>
	<525EB71C.3000504@ca.afilias.info>
	<003001ceca89$920478e0$b60d6aa0$@sgo.fr>
	<525ECDEA.8070102@ca.afilias.info>
Message-ID: <003101cecb18$697cc000$3c764000$@sgo.fr>

Hi,
This error :
 ERROR:  relation "_sloncluster.sl_local_node_id" does not exist at
character 30

Appear every 10 seconds in postgresql logs.

But i do another replication on another server (repli_local111) and no error
! same virtual server same scripts but no error...

I will try to find the problem.

-----Message d'origine-----
De?: Steve Singer [mailto:ssinger at ca.afilias.info] 
Envoy??: mercredi 16 octobre 2013 19:34
??: Sebastien Marchand
Cc?: slony1-general at lists.slony.info
Objet?: Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication

On 10/16/2013 12:05 PM, Sebastien Marchand wrote:
> No slon running because script launch slon after create set.
>
> So i launch before and IT WORKS !!! thx master ! thanks you so much
>
> I don't know what it change in slony 2.0.7 and 2.2 but before i could 
> do this
>
> But now it's ok :)
>


What SHOULD happen with 2.2 when the slon isn't running is that slonik
should keep printing:

waiting for event (1,5000000004) ...

messages, that isn't an error that is an information message saying that it
is waiting for the event to be propogated, and that won't happen unless
slonik is running.

What I don't understand is how you were getting

2013-10-15 10:55:10.950 CEST >ERROR:  relation
"_sloncluster.sl_local_node_id" does not exist at character 30


type messages.

> -----Message d'origine-----
> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi 
> 16 octobre 2013 17:56 ? : Sebastien Marchand Objet : Re: 
> [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
>
> On 10/16/2013 11:52 AM, Sebastien Marchand wrote:
>> Yes that's why i will delete all replication 2.0 and migrate 
>> postgresql after i rebuild new replication.
>>
>> when i've my  error  " waiting for event (1,5000000004) to be 
>> confirmed on node 110 " in postgresql if i do :
>>
>> select  * from _repli_local110.sl_path; => 1;110;"dbname=RPP2
>> host=192.168.0.101 port=5432 user=slony
>> password=123";10
>>
>> Why just one line ?? i need two lines !
>>
>> In my sl_event :
>>
>> 110;5000000001;"2013-10-16
>> 17:50:54.697374+02";"695958:695958:";"STORE_PATH";"1";"110";"dbname=R
>> P
>> P2
>> host=192.168.0.101 port=5432 user=slony password=123";"10";"";"";"";""
>>
>> I think there is a problem here... or not
>
> Slonik when it executes the STORE PATH , it will insert a row in 
> sl_path on each node.
>
> When slon is running it will then replicate the STORE_PATH event from 
> one node to the other to create the second sl_path row in each node.
>
> Is your slon running?
>
>
>>
>> -----Message d'origine-----
>> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi
>> 16 octobre 2013 17:02 ? : Sebastien Marchand Cc :
>> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem 
>> slony 2.2 and pg 9.3 double replication
>>
>> On 10/16/2013 10:57 AM, Sebastien Marchand wrote:
>>> I already tried to put in script but no change.
>>>
>>> Can you tell me where is the line of code that is generating this error
?
>>> it's a sql function ?
>>>
>>> I continue to search i need this to migrate.
>>
>>
>>
>> 	slon_mkquery(&query, "select max(ev_seqno) FROM \"_%s\".sl_event"
>> 				 " , \"_%s\".sl_node "
>> 				 " where ev_origin= "
>> 				 "     (select last_value from
>> \"_%s\".sl_local_node_id) "
>> 				 " AND %s AND sl_node.no_id="
>> 				 " ev_origin"
>> 				 ,script->clustername, script->clustername,
>> 				 script->clustername, event_filter);
>>
>>
>> In slonik.c
>>
>>
>> slonik_get_last_event_id(SlonikStmt * stmt,
>> 						 SlonikScript * script,
>> 						 const char *event_filter,
>> 						 int64 **events)
>>
>>
>> Also, if you are planning on migrating from 2.0 to 2.2 with UPDATE 
>> FUNCTIONS you should be aware of bug #320
>>
>>
>>>
>>> -----Message d'origine-----
>>> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi
>>> 16 octobre 2013 16:53 ? : Sebastien Marchand Cc :
>>> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem 
>>> slony 2.2 and pg 9.3 double
>> replication
>>>
>>> On 10/16/2013 10:48 AM, Steve Singer wrote:
>>>> On 10/16/2013 10:06 AM, Sebastien Marchand wrote:
>>>>>> CLUSTER NAME = repli_local110 ;
>>>>>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101
>>>>>> port=5432 user=slony password=password'; NODE 110 ADMIN CONNINFO 
>>>>>> =
>>>>>> 'dbname=RPP2 host=192.168.0.110 port=5432 user=slony 
>>>>>> password=password';
>>>>>
>>>>> It's the file repli_local110.preamble but for email i copy this 
>>>>> file in my script :)
>>>>
>>>
>>> Actually IGNORE what I said below,
>>> I hit send way too quickly before reviewing my output.
>>>
>>> I am NOT yet able to reproduce this, but try pasting your preamble 
>>> inline and see if it works.
>>>
>>> I think I see the line of code that is generating the error you are 
>>> seeing but I don't understand how/why it is substituting using 
>>> _sloncluster instead of repli_local10;
>>>
>>>
>>>
>>>
>>>> Sometimes details are important.
>>>>
>>>> Copy the preamble file inline into your script and it will work 
>>>> (like you did in your email)
>>>>
>>>> I can reproduce your issue with the preamble moved to a different file.
>>>>      This is a bug, it shouldn't be hard to fix, thanks for reporting
it.
>>>>      I suspect the fix will be included in 2.2.1 due in the next 
>>>> few weeks (since this has been a busy week for 2.2.0 bugs - ie #318 
>>>> and
>> #320).
>>>>
>>>>
>>>
>>
>


From shurale9811 at gmail.com  Fri Oct 18 01:34:50 2013
From: shurale9811 at gmail.com (Shamshe Taktayeva)
Date: Fri, 18 Oct 2013 04:34:50 -0400
Subject: [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
In-Reply-To: <003101cecb18$697cc000$3c764000$@sgo.fr>
References: <002601ceca6b$6a8f2300$3fad6900$@sgo.fr>
	<525E8F67.202@ca.afilias.info>
	<002b01ceca72$012f4280$038dc780$@sgo.fr>
	<525E949E.5070804@ca.afilias.info>
	<002c01ceca77$5f751270$1e5f3750$@sgo.fr>
	<525E9C7B.4070300@ca.afilias.info>
	<002d01ceca78$f707c190$e51744b0$@sgo.fr>
	<525EA746.2010508@ca.afilias.info>
	<525EA861.9040101@ca.afilias.info>
	<002e01ceca80$07853c80$168fb580$@sgo.fr>
	<525EAA4F.1040907@ca.afilias.info>
	<002f01ceca87$ad753b20$085fb160$@sgo.fr>
	<525EB71C.3000504@ca.afilias.info>
	<003001ceca89$920478e0$b60d6aa0$@sgo.fr>
	<525ECDEA.8070102@ca.afilias.info>
	<003101cecb18$697cc000$3c764000$@sgo.fr>
Message-ID: <CAGpgV-dT4y9uTHdmH4C3A_o+0cX1T4x5CjyJ4PxVn_bKKFdWPg@mail.gmail.com>

The problem is that starting with slony 2.1 slon connects to the database
using parameter conninfo and init script takes it from
/etc/sysconfig/slony1-93(which is redundant), moreover by default it
connects to postgres on localhost not to the database you are replicating ,
cannot find _slonycluster schema and throws above error. Adding database
name to /etc/sysconfig/slony1-93 won't help

I've changed in the init script /etc/init.d/slony1-93  the following line:
$SU -l postgres -c "$SLONDAEMON -f $SLONCONF -p $SLONPID $SLONCLUSTERNAME
$SLONCONNINFO &" >> "$SLONLOGDIR/slonystartup.log" 2>&1 < /dev/null
to
 $SU -l postgres -c "$SLONDAEMON -f $SLONCONF -p $SLONPID $SLONCLUSTERNAME
'$SLONCONNINFO' &" >> "$SLONLOGDIR/slonystartup.log" 2>&1 < /dev/null

and that solved the problem


Shamshinur Taktayeva
shurale9811 at gmail.com
mob:4164536209


On Thu, Oct 17, 2013 at 5:08 AM, Sebastien Marchand <smarchand at sgo.fr>wrote:

> Hi,
> This error :
>  ERROR:  relation "_sloncluster.sl_local_node_id" does not exist at
> character 30
>
> Appear every 10 seconds in postgresql logs.
>
> But i do another replication on another server (repli_local111) and no
> error
> ! same virtual server same scripts but no error...
>
> I will try to find the problem.
>
> -----Message d'origine-----
> De : Steve Singer [mailto:ssinger at ca.afilias.info]
> Envoy? : mercredi 16 octobre 2013 19:34
> ? : Sebastien Marchand
> Cc : slony1-general at lists.slony.info
> Objet : Re: [Slony1-general] Problem slony 2.2 and pg 9.3 double
> replication
>
> On 10/16/2013 12:05 PM, Sebastien Marchand wrote:
> > No slon running because script launch slon after create set.
> >
> > So i launch before and IT WORKS !!! thx master ! thanks you so much
> >
> > I don't know what it change in slony 2.0.7 and 2.2 but before i could
> > do this
> >
> > But now it's ok :)
> >
>
>
> What SHOULD happen with 2.2 when the slon isn't running is that slonik
> should keep printing:
>
> waiting for event (1,5000000004) ...
>
> messages, that isn't an error that is an information message saying that it
> is waiting for the event to be propogated, and that won't happen unless
> slonik is running.
>
> What I don't understand is how you were getting
>
> 2013-10-15 10:55:10.950 CEST >ERROR:  relation
> "_sloncluster.sl_local_node_id" does not exist at character 30
>
>
> type messages.
>
> > -----Message d'origine-----
> > De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi
> > 16 octobre 2013 17:56 ? : Sebastien Marchand Objet : Re:
> > [Slony1-general] Problem slony 2.2 and pg 9.3 double replication
> >
> > On 10/16/2013 11:52 AM, Sebastien Marchand wrote:
> >> Yes that's why i will delete all replication 2.0 and migrate
> >> postgresql after i rebuild new replication.
> >>
> >> when i've my  error  " waiting for event (1,5000000004) to be
> >> confirmed on node 110 " in postgresql if i do :
> >>
> >> select  * from _repli_local110.sl_path; => 1;110;"dbname=RPP2
> >> host=192.168.0.101 port=5432 user=slony
> >> password=123";10
> >>
> >> Why just one line ?? i need two lines !
> >>
> >> In my sl_event :
> >>
> >> 110;5000000001;"2013-10-16
> >> 17:50:54.697374+02";"695958:695958:";"STORE_PATH";"1";"110";"dbname=R
> >> P
> >> P2
> >> host=192.168.0.101 port=5432 user=slony password=123";"10";"";"";"";""
> >>
> >> I think there is a problem here... or not
> >
> > Slonik when it executes the STORE PATH , it will insert a row in
> > sl_path on each node.
> >
> > When slon is running it will then replicate the STORE_PATH event from
> > one node to the other to create the second sl_path row in each node.
> >
> > Is your slon running?
> >
> >
> >>
> >> -----Message d'origine-----
> >> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi
> >> 16 octobre 2013 17:02 ? : Sebastien Marchand Cc :
> >> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem
> >> slony 2.2 and pg 9.3 double replication
> >>
> >> On 10/16/2013 10:57 AM, Sebastien Marchand wrote:
> >>> I already tried to put in script but no change.
> >>>
> >>> Can you tell me where is the line of code that is generating this error
> ?
> >>> it's a sql function ?
> >>>
> >>> I continue to search i need this to migrate.
> >>
> >>
> >>
> >>      slon_mkquery(&query, "select max(ev_seqno) FROM \"_%s\".sl_event"
> >>                               " , \"_%s\".sl_node "
> >>                               " where ev_origin= "
> >>                               "     (select last_value from
> >> \"_%s\".sl_local_node_id) "
> >>                               " AND %s AND sl_node.no_id="
> >>                               " ev_origin"
> >>                               ,script->clustername, script->clustername,
> >>                               script->clustername, event_filter);
> >>
> >>
> >> In slonik.c
> >>
> >>
> >> slonik_get_last_event_id(SlonikStmt * stmt,
> >>                                               SlonikScript * script,
> >>                                               const char *event_filter,
> >>                                               int64 **events)
> >>
> >>
> >> Also, if you are planning on migrating from 2.0 to 2.2 with UPDATE
> >> FUNCTIONS you should be aware of bug #320
> >>
> >>
> >>>
> >>> -----Message d'origine-----
> >>> De : Steve Singer [mailto:ssinger at ca.afilias.info] Envoy? : mercredi
> >>> 16 octobre 2013 16:53 ? : Sebastien Marchand Cc :
> >>> slony1-general at lists.slony.info Objet : Re: [Slony1-general] Problem
> >>> slony 2.2 and pg 9.3 double
> >> replication
> >>>
> >>> On 10/16/2013 10:48 AM, Steve Singer wrote:
> >>>> On 10/16/2013 10:06 AM, Sebastien Marchand wrote:
> >>>>>> CLUSTER NAME = repli_local110 ;
> >>>>>> NODE 101 ADMIN CONNINFO = 'dbname=RPP2 host=192.168.0.101
> >>>>>> port=5432 user=slony password=password'; NODE 110 ADMIN CONNINFO
> >>>>>> =
> >>>>>> 'dbname=RPP2 host=192.168.0.110 port=5432 user=slony
> >>>>>> password=password';
> >>>>>
> >>>>> It's the file repli_local110.preamble but for email i copy this
> >>>>> file in my script :)
> >>>>
> >>>
> >>> Actually IGNORE what I said below,
> >>> I hit send way too quickly before reviewing my output.
> >>>
> >>> I am NOT yet able to reproduce this, but try pasting your preamble
> >>> inline and see if it works.
> >>>
> >>> I think I see the line of code that is generating the error you are
> >>> seeing but I don't understand how/why it is substituting using
> >>> _sloncluster instead of repli_local10;
> >>>
> >>>
> >>>
> >>>
> >>>> Sometimes details are important.
> >>>>
> >>>> Copy the preamble file inline into your script and it will work
> >>>> (like you did in your email)
> >>>>
> >>>> I can reproduce your issue with the preamble moved to a different
> file.
> >>>>      This is a bug, it shouldn't be hard to fix, thanks for reporting
> it.
> >>>>      I suspect the fix will be included in 2.2.1 due in the next
> >>>> few weeks (since this has been a busy week for 2.2.0 bugs - ie #318
> >>>> and
> >> #320).
> >>>>
> >>>>
> >>>
> >>
> >
>
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20131018/ddae5ff1/attachment.htm 

