From ragavendra.dba at gmail.com  Mon Jul  1 04:42:30 2013
From: ragavendra.dba at gmail.com (Raghav)
Date: Mon, 1 Jul 2013 17:12:30 +0530
Subject: [Slony1-general] SlonyBeta 2.2 Question ?
Message-ID: <CANwAqWhuqH=rOdBqUf9rsrrJxcsunJ_pR=GkJP+-iV2yUMF-2Q@mail.gmail.com>

Hi,

Firstly, many thanks for new release of Slony 2.2Beta.

I am testing the new beta, I observed few things and want to know from here
if am missing anything.

1. Executing any DDL on replicating table will crash the replication and
error out as below:

2013-06-15 12:31:17 IST ERROR  remoteWorkerThread_1: "insert into
"public"."stest" ("id","name") values ('1','asdf');
" ERROR:  column "name" of relation "stest" does not exist
LINE 1: insert into "public"."stest" ("id","name") values ('1','asdf...
2013-06-15 12:31:17 IST DEBUG2 remoteWorkerThread_1: cleanup
2013-06-15 12:31:17 IST ERROR  remoteWorkerThread_1: SYNC aborted

But the same is not happening in BETA (I have executed ALTER TABLE
command). Am I missing anything here ?

2. Does slony archives(slon -a) capture DDL events in .sql file ?


-- 

Regards
Raghav
Blog: htt://raghavt.blogspot.com/
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20130701/7579cc33/attachment.html 

From ssinger at ca.afilias.info  Mon Jul  1 09:37:47 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Mon, 01 Jul 2013 12:37:47 -0400
Subject: [Slony1-general] SlonyBeta 2.2 Question ?
In-Reply-To: <CANwAqWhuqH=rOdBqUf9rsrrJxcsunJ_pR=GkJP+-iV2yUMF-2Q@mail.gmail.com>
References: <CANwAqWhuqH=rOdBqUf9rsrrJxcsunJ_pR=GkJP+-iV2yUMF-2Q@mail.gmail.com>
Message-ID: <51D1B05B.8010609@ca.afilias.info>

On 07/01/2013 07:42 AM, Raghav wrote:
> Hi,
>
> Firstly, many thanks for new release of Slony 2.2Beta.

Thanks for trying to test the beta.

>
> I am testing the new beta, I observed few things and want to know from
> here if am missing anything.
>
> 1. Executing any DDL on replicating table will crash the replication and
> error out as below:
>
> 2013-06-15 12:31:17 IST ERROR  remoteWorkerThread_1: "insert into
> "public"."stest" ("id","name") values ('1','asdf');
> " ERROR:  column "name" of relation "stest" does not exist

What does your table stest look like on the replica?  Does it have a 
column "name" ?

What DDL did you execute and in what order?  If you are adding or 
dropping the "name" column then this sounds like a bug, but more details 
so we can reproduce this would be helpful.

> LINE 1: insert into "public"."stest" ("id","name") values ('1','asdf...
> 2013-06-15 12:31:17 IST DEBUG2 remoteWorkerThread_1: cleanup
> 2013-06-15 12:31:17 IST ERROR  remoteWorkerThread_1: SYNC aborted
>
> But the same is not happening in BETA (I have executed ALTER TABLE
> command). Am I missing anything here ?
>
> 2. Does slony archives(slon -a) capture DDL events in .sql file ?
>
>

Looking at the code, I *think* the DDL events will show up in the the 
.sql files as part of the copy stream, but the apply trigger the 
slony1_dump.sh installs on the log shipping node won't process them. 
This sounds like a bug/oversight.



> --
>
> Regards
> Raghav
> Blog: htt://raghavt.blogspot.com/ <http://raghavt.blogspot.com/>
>
>
> _______________________________________________
> Slony1-general mailing list
> Slony1-general at lists.slony.info
> http://lists.slony.info/mailman/listinfo/slony1-general


From ragavendra.dba at gmail.com  Tue Jul  2 09:11:06 2013
From: ragavendra.dba at gmail.com (Raghav)
Date: Tue, 2 Jul 2013 21:41:06 +0530
Subject: [Slony1-general] SlonyBeta 2.2 Question ?
In-Reply-To: <51D1B05B.8010609@ca.afilias.info>
References: <CANwAqWhuqH=rOdBqUf9rsrrJxcsunJ_pR=GkJP+-iV2yUMF-2Q@mail.gmail.com>
	<51D1B05B.8010609@ca.afilias.info>
Message-ID: <CANwAqWhcHqPf=YX3U_X3iEy5+F00mV61HxX8PG-BDrkoBBn2+Q@mail.gmail.com>

> What does your table stest look like on the replica?  Does it have a
> column "name" ?
>
> What DDL did you execute and in what order?  If you are adding or dropping
> the "name" column then this sounds like a bug, but more details so we can
> reproduce this would be helpful.
>

Sure. I have created a test case and implemented on both slony versions,
stabled(2.1.2) & BETA(2.2.0).

Steps:
1. Create a table with one column and few rows:
    create table stest(id int primary key);
    insert into stest values(generate_series(1,5));
2. Configure slony (initialization, create & subscribe) in SLON ARCHIVE
mode(slon -a).
3. Once sync catch up, execute DDL command without using EXECUTE SCRIPT
(like user error)
ALTER TABLE STEST ADD COLUMN NAME TEXT;
INSERT INTO STEST VALUES (10,'TEST);

Observations in Slony 2.1.2 on above scenario:

1. DDL caused replication to crash if its executed without using EXECUTE
SCRIPT(expected behavior) . Below log message is example of crash when I
executed a DDL.

2013-06-15 16:36:26 IST ERROR  remoteWorkerThread_1: "insert into
"public"."stest" ("id","name") values (10,'TEST');
" ERROR:  column "name" of relation "stest" does not exist
LINE 1: insert into "public"."stest" ("id","name") values ('1','...
....
2013-06-15 16:36:26 IST ERROR  remoteWorkerThread_1: SYNC aborted

2. Archives didn't captured the ALTER TABLE command, however an INSERT
immediate after ALTER has been captured in archives.
-bash-4.1$ fgrep -i alter *
-bash-4.1$ fgrep -i insert *
slony1_log_2_00000000000000000021.sql.tmp:insert into "public"."stest"
("id","name") values ('10','TEST');

Observation in 2.2.0B on above scenario:

1.  Executing DDL, didn't impact the replication whatsoever, in the sense
it didn't crashed. It just paused the replication. (I waited for almost 15
minuts and tried few DMLs on the table).
2.  Interesting, neither DDL nor DML's captured by archives in this version.
-bash-4.1$ fgrep -i alter *
-bash-4.1$ fgrep -i insert *
-bash-4.1$

Please let me know if any further information required from my end.

--Raghav
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20130702/82be2358/attachment.htm 

From ssinger at ca.afilias.info  Tue Jul  2 10:46:28 2013
From: ssinger at ca.afilias.info (Steve Singer)
Date: Tue, 02 Jul 2013 13:46:28 -0400
Subject: [Slony1-general] SlonyBeta 2.2 Question ?
In-Reply-To: <CANwAqWhcHqPf=YX3U_X3iEy5+F00mV61HxX8PG-BDrkoBBn2+Q@mail.gmail.com>
References: <CANwAqWhuqH=rOdBqUf9rsrrJxcsunJ_pR=GkJP+-iV2yUMF-2Q@mail.gmail.com>
	<51D1B05B.8010609@ca.afilias.info>
	<CANwAqWhcHqPf=YX3U_X3iEy5+F00mV61HxX8PG-BDrkoBBn2+Q@mail.gmail.com>
Message-ID: <51D311F4.9000507@ca.afilias.info>

On 07/02/2013 12:11 PM, Raghav wrote:
>
>     What does your table stest look like on the replica?  Does it have a
>     column "name" ?
>
>     What DDL did you execute and in what order?  If you are adding or
>     dropping the "name" column then this sounds like a bug, but more
>     details so we can reproduce this would be helpful.
>
>
> Sure. I have created a test case and implemented on both slony versions,
> stabled(2.1.2) & BETA(2.2.0).
>
> Steps:
> 1. Create a table with one column and few rows:
>      create table stest(id int primary key);
>      insert into stest values(generate_series(1,5));
> 2. Configure slony (initialization, create & subscribe) in SLON ARCHIVE
> mode(slon -a).
> 3. Once sync catch up, execute DDL command without using EXECUTE SCRIPT
> (like user error)
> ALTER TABLE STEST ADD COLUMN NAME TEXT;
> INSERT INTO STEST VALUES (10,'TEST);
>
> Observations in Slony 2.1.2 on above scenario:
>
> 1. DDL caused replication to crash if its executed without using EXECUTE
> SCRIPT(expected behavior) . Below log message is example of crash when I
> executed a DDL.
>
> 2013-06-15 16:36:26 IST ERROR  remoteWorkerThread_1: "insert into
> "public"."stest" ("id","name") values (10,'TEST');
> " ERROR:  column "name" of relation "stest" does not exist
> LINE 1: insert into "public"."stest" ("id","name") values ('1','...
> ....
> 2013-06-15 16:36:26 IST ERROR  remoteWorkerThread_1: SYNC aborted
>
> 2. Archives didn't captured the ALTER TABLE command, however an INSERT
> immediate after ALTER has been captured in archives.
> -bash-4.1$ fgrep -i alter *
> -bash-4.1$ fgrep -i insert *
> slony1_log_2_00000000000000000021.sql.tmp:insert into "public"."stest"
> ("id","name") values ('10','TEST');
>
> Observation in 2.2.0B on above scenario:
>
> 1.  Executing DDL, didn't impact the replication whatsoever, in the
> sense it didn't crashed. It just paused the replication. (I waited for
> almost 15 minuts and tried few DMLs on the table).

I can reproduce this.  Replication stops and I see things in the slon 
log like:


2013-07-02 13:39:03 EDT INFO   remoteWorkerThread_1: syncing set 1 with 
1 table(s) from provider 1
2013-07-02 13:39:03 EDT ERROR  remoteWorkerThread_1_1: error at end of 
COPY IN: ERROR:  Slony-I: type lookup for column name failed in logApply()
CONTEXT:  COPY sl_log_1, line 1: "1	1068182	1	1	public	stest	I	0 
{id,10,name,TEST}"



This is the new error that you get with slony 2.2.  That is the 
behaviour I would expect, very similar to 2.1 except the message is 
different


> 2.  Interesting, neither DDL nor DML's captured by archives in this version.
> -bash-4.1$ fgrep -i alter *
> -bash-4.1$ fgrep -i insert *
> -bash-4.1$
>

The DML actually is captured (at least for me) but the .sql files in 2.2 
use COPY not insert.

Try
fgrep -i stest *

Mine looks like:

COPY "_test"."sl_log_archive" ( log_origin, 
log_txid,log_tableid,log_actionseq,log_tablenspname, log_tablerelname, 
log_cmdtype, log_cmdupdncols,log_cmdargs) FROM STDIN;
1       1068182 1       1       public  stest   I       0 
{id,10,name,TEST}


The DDL isn't captured though, this is an omission that we probably 
should fix.

Also, are there places in the documentation where we need to be more 
clear on the changes in 2.2, particularly saying that the log shipping 
format has changed ? ( I am open to ideas on where)




> Please let me know if any further information required from my end.
>
> --Raghav


From ragavendra.dba at gmail.com  Wed Jul  3 01:53:45 2013
From: ragavendra.dba at gmail.com (Raghav)
Date: Wed, 3 Jul 2013 14:23:45 +0530
Subject: [Slony1-general] SlonyBeta 2.2 Question ?
In-Reply-To: <51D311F4.9000507@ca.afilias.info>
References: <CANwAqWhuqH=rOdBqUf9rsrrJxcsunJ_pR=GkJP+-iV2yUMF-2Q@mail.gmail.com>
	<51D1B05B.8010609@ca.afilias.info>
	<CANwAqWhcHqPf=YX3U_X3iEy5+F00mV61HxX8PG-BDrkoBBn2+Q@mail.gmail.com>
	<51D311F4.9000507@ca.afilias.info>
Message-ID: <CANwAqWjG3EW9bfF5ycohy6Jqc7fHZcih8RFPcCFKaPucdzVHqg@mail.gmail.com>

> I can reproduce this.  Replication stops and I see things in the slon log
> like:
>
>
> 2013-07-02 13:39:03 EDT INFO   remoteWorkerThread_1: syncing set 1 with 1
> table(s) from provider 1
> 2013-07-02 13:39:03 EDT ERROR  remoteWorkerThread_1_1: error at end of
> COPY IN: ERROR:  Slony-I: type lookup for column name failed in logApply()
> CONTEXT:  COPY sl_log_1, line 1: "1     1068182 1       1       public
>  stest   I       0 {id,10,name,TEST}"
>
>
I couldn't able to generate this error within my setup, beyond any doubt I
may be doing something not right.
Its been a while am monitoring the logs after executing manual DDL on
replication table, replication doesn't crashes. But st_lag_time &
st_lag_num_events of sl_status keep increasing.

postgres=# select * from _newbuild.sl_status ;
-[ RECORD 1 ]-------------+---------------------------------
st_origin                 | 1
st_received               | 2
st_last_event             | 5000000041
st_last_event_ts          | 2013-06-15 19:52:38.989129+05:30
st_last_received          | 5000000021
st_last_received_ts       | 2013-06-15 23:17:10.608269+05:30
st_last_received_event_ts | 2013-06-15 19:49:18.801361+05:30
st_lag_num_events         | 20
st_lag_time               | 05:00:22.268792



> 2.  Interesting, neither DDL nor DML's captured by archives in this
>> version.
>> -bash-4.1$ fgrep -i alter *
>> -bash-4.1$ fgrep -i insert *
>> -bash-4.1$
>
> The DML actually is captured (at least for me) but the .sql files in 2.2
> use COPY not insert.
>
> Try
> fgrep -i stest *
>
> Mine looks like:
>
> COPY "_test"."sl_log_archive" ( log_origin, log_txid,log_tableid,log_**actionseq,log_tablenspname,
> log_tablerelname, log_cmdtype, log_cmdupdncols,log_cmdargs) FROM STDIN;
> 1       1068182 1       1       public  stest   I       0 {id,10,name,TEST}
>
>
Yeah, actually, I read in the BETA documentation about this section that
now data storing/transferring in sl_log_1/sl_log_2 has changed its protocol
to COPY  instead of DML events. I have watched this changes while testing
but due to dual versions testing I executed fgrep command with INSERT
instead of COPY. Thanks for correcting.

Previous
==> slony1_log_2_00000000000000000005.sql <==
-- start of Slony-I data
------------------------------------------------------------------
insert into "public"."stest" ("id") values ('103');

Latest:
==> slony1_log_2_00000000000000000006.sql <==
------------------------------------------------------------------
COPY "_rep220"."sl_log_archive" ( log_origin,
log_txid,log_tableid,log_actionseq,log_tablenspname, log_tablerelname,
log_cmdtype, log_cmdupdnc
ols,log_cmdargs) FROM STDIN;
1       565688  1       2       public  stest   I       0       {id,1000}
\.



> The DDL isn't captured though, this is an omission that we probably should
> fix.
>

Seems its not captured in earlier version too ? am i right. So it would be
a feature request to include DDLs in .sql files.

Also, are there places in the documentation where we need to be more clear
> on the changes in 2.2, particularly saying that the log shipping format has
> changed ? ( I am open to ideas on where)
>

Just two areas:
http://slony.info/documentation/2.1/logshipping.html

http://slony.info/documentation/slon.html
-a option section.


--
Regards
Raghav
Blog: htt://raghavt.blogspot.com/
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20130703/3461b641/attachment.htm 

From vivek at khera.org  Wed Jul  3 08:15:04 2013
From: vivek at khera.org (Vick Khera)
Date: Wed, 3 Jul 2013 11:15:04 -0400
Subject: [Slony1-general] test_slony_state-dbi.pl
In-Reply-To: <51CDD9C0.1000602@ca.afilias.info>
References: <51CDD9C0.1000602@ca.afilias.info>
Message-ID: <CALd+dcf9wU=tvU8BrqjN5bKbh3=_6WD8L4n-FQpCs+zNqqb8cQ@mail.gmail.com>

On Fri, Jun 28, 2013 at 2:45 PM, Steve Singer <ssinger at ca.afilias.info>wrote:

> I am wondering who else is actually using the test_slony_state script
> that we include in slony1-engine/tools
>

I do not use it. I use a custom script I put together for nagios that
simply returns the number of seconds behind that my replica is from the
origin, and trigger based on that number any alerts I need.
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20130703/ea57adf2/attachment.htm 

From ragavendra.dba at gmail.com  Thu Jul  4 00:50:27 2013
From: ragavendra.dba at gmail.com (Raghav)
Date: Thu, 4 Jul 2013 13:20:27 +0530
Subject: [Slony1-general] RESUBSCRIBE NODE in 2.2.0Beta
Message-ID: <CANwAqWi8hfOe2O6GkbBU=vrLebHSr9=RH9pDNcKqN9xddOsybw@mail.gmail.com>

Hi,

I've three nodes configured using Slony 2.2.0B/PG 9.3beta with One master
two slaves and one table.


        Node1 (Master - 5555)
                      |
        --------------------------------
        |                          |
Slave1-5556          Slave2- 5557

As per doc, RESUBSCRIBE NODE its says we could change the provider. So,
planned to move Provider to Slave1-5556 (node 2).

"The RESUBSCRIBE NODE command will change the provider used to receive data
from for all of the replication sets originating on a given node. If a
subscriber node is receiving a number of replication sets with a particular
node as an origin then the RESUBSCRIBE NODE command will change the
provider node used by that subscriber node for all of the replication sets
originating on the given origin."

Hence, I have created a script to perform RESUBSCRIBE NODE:

Resub.sh script:

cluster name = rep220;
node 1 admin conninfo='host=localhost dbname=postgres user=postgres
port=5555';
node 2 admin conninfo='host=localhost dbname=postgres user=postgres
port=5556';
node 3 admin conninfo='host=localhost dbname=postgres user=postgres
port=5557';
resubscribe node ( origin = 1, provider = 2 , receiver = 3);

While executing it gives me error as:

-bash-4.1$ slonik resub_set.sh
resub_set.sh:8: PGRES_FATAL_ERROR lock table "_rep220".sl_event_lock,
"_rep220".sl_config_lock;select "_rep220".resubscribeNode(1, 2, 2);  -
ERROR:  insert or update on table "sl_subscribe" violates foreign key
constraint "sl_subscribe-sl_path-ref"
DETAIL:  Key (sub_provider, sub_receiver)=(2, 2) is not present in table
"sl_path".
CONTEXT:  SQL statement "update "_rep220".sl_subscribe
                        set sub_provider = p_sub_provider,
                                sub_forward = p_sub_forward
                        where sub_set = p_sub_set
                        and sub_receiver = p_sub_receiver"
PL/pgSQL function
_rep220.subscribeset_int(integer,integer,integer,boolean,boolean) line 35
at SQL statement
SQL statement "SELECT "_rep220".subscribeSet_int(v_record.sub_set,
                                p_provider,
                                p_receiver, v_record.sub_forward, false)"
PL/pgSQL function _rep220.resubscribenode(integer,integer,integer) line 75
at PERFORM
-bash-4.1$

Here's sl_path output from three nodes:

sl_path ouput from 5555 port

postgres=# select * from _rep220.sl_path ;
 pa_server | pa_client |                      pa_conninfo
    | pa_connretry
-----------+-----------+--------------------------------------------------------+--------------
         2 |         1 | host=localhost dbname=postgres user=postgres
port=5556 |           10
         1 |         2 | host=localhost dbname=postgres user=postgres
port=5555 |           10
         3 |         1 | host=localhost dbname=postgres user=postgres
port=5557 |           10
         1 |         3 | host=localhost dbname=postgres user=postgres
port=5555 |           10
(4 rows)

sl_path ouput from 5556 port

-bash-4.1$ psql -p 5556
psql (9.3beta1)
Type "help" for help.

postgres=# select * from _rep220.sl_path ;
 pa_server | pa_client |                      pa_conninfo
    | pa_connretry
-----------+-----------+--------------------------------------------------------+--------------
         1 |         2 | host=localhost dbname=postgres user=postgres
port=5555 |           10
         2 |         1 | host=localhost dbname=postgres user=postgres
port=5556 |           10
         3 |         1 | host=localhost dbname=postgres user=postgres
port=5557 |           10
         1 |         3 | host=localhost dbname=postgres user=postgres
port=5555 |           10
(4 rows)

sl_path ouput from 5557 port

-bash-4.1$ psql -p 5557
psql (9.3beta1)
Type "help" for help.

postgres=# select * from _rep220.sl_path ;
 pa_server | pa_client |                      pa_conninfo
    | pa_connretry
-----------+-----------+--------------------------------------------------------+--------------
         2 |         1 | host=localhost dbname=postgres user=postgres
port=5556 |           10
         1 |         2 | host=localhost dbname=postgres user=postgres
port=5555 |           10
         1 |         3 | host=localhost dbname=postgres user=postgres
port=5555 |           10
         3 |         1 | host=localhost dbname=postgres user=postgres
port=5557 |           10
(4 rows)

I may be doing something surely wrong here, would you please indicate me
what mix-up am doing here.

Thanks in advance.

-- 
Regards
Raghav
Blog: htt://raghavt.blogspot.com/
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20130704/aec9f605/attachment.htm 

From ragavendra.dba at gmail.com  Thu Jul  4 01:00:13 2013
From: ragavendra.dba at gmail.com (Raghav)
Date: Thu, 4 Jul 2013 13:30:13 +0530
Subject: [Slony1-general] RESUBSCRIBE NODE in 2.2.0Beta
In-Reply-To: <CANwAqWi8hfOe2O6GkbBU=vrLebHSr9=RH9pDNcKqN9xddOsybw@mail.gmail.com>
References: <CANwAqWi8hfOe2O6GkbBU=vrLebHSr9=RH9pDNcKqN9xddOsybw@mail.gmail.com>
Message-ID: <CANwAqWgyHuriYhpYFLuXNChEWiS-oZ+B6_qsvVr+zSLrWdNmeQ@mail.gmail.com>

>
>
> Hence, I have created a script to perform RESUBSCRIBE NODE:
>
> Resub.sh script:
>
> cluster name = rep220;
> node 1 admin conninfo='host=localhost dbname=postgres user=postgres
> port=5555';
> node 2 admin conninfo='host=localhost dbname=postgres user=postgres
> port=5556';
> node 3 admin conninfo='host=localhost dbname=postgres user=postgres
> port=5557';
> resubscribe node ( origin = 1, provider = 2 , receiver = 3);
>
> While executing it gives me error as:
>
> -bash-4.1$ slonik resub_set.sh
> resub_set.sh:8: PGRES_FATAL_ERROR lock table "_rep220".sl_event_lock,
> "_rep220".sl_config_lock;select "_rep220".resubscribeNode(1, 2, 2);  -
>


> ERROR:  insert or update on table "sl_subscribe" violates foreign key
> constraint "sl_subscribe-sl_path-ref"
> DETAIL:  Key (sub_provider, sub_receiver)=(2, 2) is not present in table
> "sl_path".
>

Merely a blind guess, any step  ( between 5556 to 5557) I missed before
executing RESUBSCRIBE NODE.

--Raghav
-------------- next part --------------
An HTML attachment was scrubbed...
URL: http://lists.slony.info/pipermail/slony1-general/attachments/20130704/c673f79d/attachment.htm 

